using System.Data;using System.Text.RegularExpressions;using Microsoft.EntityFrameworkCore;using Microsoft.EntityFrameworkCore.Storage;using verii_metivon_api.Core.Persistence;using verii_metivon_api.Modules.Parameters.Domain.Entities;using verii_metivon_api.Modules.Transfers.Domain.Entities;
namespace verii_metivon_api.Modules.Transfers.Application.Parameters;
public sealed record TransferParametersDto(long?BranchId,long?WarehouseId,bool IsAutomatic,bool AllowManual,string Format,long NextNumber,int IncrementBy,long MinimumNumber,long MaximumNumber,bool IsContinuous,bool AllowCrossBranchTransfer,bool RequireConfirmationBeforeShipment,bool AutoConfirmOnCreate,bool RequireExpectedReceiptDate,int DefaultTransitDays,bool AllowPastTransferDate,bool AllowReceiptBeforeExpectedDate,bool RequireNotes,int MaximumLinesPerTransfer,bool RequireLotForLotTracked,bool RequireSerialForSerialTracked,long?DefaultInventoryStatusId,string InventoryCurrencyCode,string Preview);
public sealed record SaveTransferParametersRequest(long?BranchId,long?WarehouseId,bool IsAutomatic,bool AllowManual,string Format,long NextNumber,int IncrementBy,long MinimumNumber,long MaximumNumber,bool IsContinuous,bool AllowCrossBranchTransfer,bool RequireConfirmationBeforeShipment,bool AutoConfirmOnCreate,bool RequireExpectedReceiptDate,int DefaultTransitDays,bool AllowPastTransferDate,bool AllowReceiptBeforeExpectedDate,bool RequireNotes,int MaximumLinesPerTransfer,bool RequireLotForLotTracked,bool RequireSerialForSerialTracked,long?DefaultInventoryStatusId,string InventoryCurrencyCode);
public interface ITransferParameterService{Task<TransferParametersDto>GetAsync(long?branchId,long?warehouseId,CancellationToken ct);Task<TransferParametersDto>SaveAsync(SaveTransferParametersRequest r,CancellationToken ct);Task<TransferParameterSettings>ResolveSettingsAsync(long?branchId,long?warehouseId,CancellationToken ct);Task<string>ResolveNumberAsync(string?requested,long?branchId,CancellationToken ct);}
public sealed class TransferParameterService(MetivonDbContext db):ITransferParameterService
{
 const string Module="Transfers",Reference="TransferNumber";static readonly Regex Token=new(@"\{NUMBER(?::(?<length>\d{1,2}))?\}",RegexOptions.Compiled|RegexOptions.IgnoreCase);
 public async Task<TransferParametersDto>GetAsync(long?branchId,long?warehouseId,CancellationToken ct){var s=await Sequence(branchId,ct);var p=await ResolveSettingsAsync(branchId,warehouseId,ct);return Map(s,p,await BranchCode(branchId,ct),warehouseId);}
 public async Task<TransferParametersDto>SaveAsync(SaveTransferParametersRequest r,CancellationToken ct){Validate(r);await ValidateRefs(r,ct);await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var s=await db.NumberSequences.FirstOrDefaultAsync(x=>x.Module==Module&&x.Reference==Reference&&x.BranchId==r.BranchId,ct);if(s is null){s=new NumberSequence{Module=Module,Reference=Reference,BranchId=r.BranchId};db.Add(s);}s.Format=r.Format.Trim();s.CurrentNumber=r.NextNumber;s.IncrementBy=r.IncrementBy;s.MinimumNumber=r.MinimumNumber;s.MaximumNumber=r.MaximumNumber;s.IsAutomatic=r.IsAutomatic;s.AllowManual=r.AllowManual;s.IsContinuous=r.IsContinuous;s.IsActive=true;var p=await db.TransferParameterSettings.FirstOrDefaultAsync(x=>x.BranchId==r.BranchId&&x.WarehouseId==r.WarehouseId,ct);if(p is null){p=new TransferParameterSettings{BranchId=r.BranchId,WarehouseId=r.WarehouseId};db.Add(p);}Apply(p,r);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return await GetAsync(r.BranchId,r.WarehouseId,ct);}
 public async Task<TransferParameterSettings>ResolveSettingsAsync(long?branchId,long?warehouseId,CancellationToken ct)=>await db.TransferParameterSettings.AsNoTracking().Where(x=>(x.BranchId==branchId||x.BranchId==null)&&(x.WarehouseId==warehouseId||x.WarehouseId==null)).OrderByDescending(x=>x.WarehouseId.HasValue).ThenByDescending(x=>x.BranchId.HasValue).FirstOrDefaultAsync(ct)??new TransferParameterSettings{BranchId=branchId,WarehouseId=warehouseId};
 public async Task<string>ResolveNumberAsync(string?requested,long?branchId,CancellationToken ct){var s=await Sequence(branchId,ct);var manual=requested?.Trim().ToUpperInvariant();if(!string.IsNullOrWhiteSpace(manual)){if(s.IsAutomatic&&!s.AllowManual)throw new InvalidOperationException("Manual transfer number is not allowed by transfer parameters.");return manual;}if(!s.IsAutomatic)throw new InvalidOperationException("Transfer number is required because automatic numbering is disabled.");return Format(s.Format,await Consume(s,ct),await BranchCode(branchId,ct));}
 async Task<NumberSequence>Sequence(long?branchId,CancellationToken ct)=>await db.NumberSequences.AsNoTracking().Where(x=>x.Module==Module&&x.Reference==Reference&&x.IsActive&&(x.BranchId==branchId||x.BranchId==null)).OrderByDescending(x=>x.BranchId.HasValue).FirstOrDefaultAsync(ct)??new NumberSequence{Module=Module,Reference=Reference,BranchId=branchId,Format="TR-{YYYY}-{NUMBER:6}",CurrentNumber=1,IncrementBy=1,MinimumNumber=1,MaximumNumber=999999999,IsAutomatic=true,AllowManual=true};
 async Task<string>BranchCode(long?id,CancellationToken ct)=>id.HasValue?await db.Branches.AsNoTracking().Where(x=>x.Id==id).Select(x=>x.Code).FirstOrDefaultAsync(ct)??"0":"0";
 static TransferParametersDto Map(NumberSequence s,TransferParameterSettings p,string branch,long?warehouseId)=>new(s.BranchId,warehouseId,s.IsAutomatic,s.AllowManual,s.Format,s.CurrentNumber,s.IncrementBy,s.MinimumNumber,s.MaximumNumber,s.IsContinuous,p.AllowCrossBranchTransfer,p.RequireConfirmationBeforeShipment,p.AutoConfirmOnCreate,p.RequireExpectedReceiptDate,p.DefaultTransitDays,p.AllowPastTransferDate,p.AllowReceiptBeforeExpectedDate,p.RequireNotes,p.MaximumLinesPerTransfer,p.RequireLotForLotTracked,p.RequireSerialForSerialTracked,p.DefaultInventoryStatusId,p.InventoryCurrencyCode,Format(s.Format,s.CurrentNumber,branch));
 static void Apply(TransferParameterSettings p,SaveTransferParametersRequest r){p.AllowCrossBranchTransfer=r.AllowCrossBranchTransfer;p.RequireConfirmationBeforeShipment=r.RequireConfirmationBeforeShipment;p.AutoConfirmOnCreate=r.AutoConfirmOnCreate;p.RequireExpectedReceiptDate=r.RequireExpectedReceiptDate;p.DefaultTransitDays=r.DefaultTransitDays;p.AllowPastTransferDate=r.AllowPastTransferDate;p.AllowReceiptBeforeExpectedDate=r.AllowReceiptBeforeExpectedDate;p.RequireNotes=r.RequireNotes;p.MaximumLinesPerTransfer=r.MaximumLinesPerTransfer;p.RequireLotForLotTracked=r.RequireLotForLotTracked;p.RequireSerialForSerialTracked=r.RequireSerialForSerialTracked;p.DefaultInventoryStatusId=r.DefaultInventoryStatusId;p.InventoryCurrencyCode=r.InventoryCurrencyCode.Trim().ToUpperInvariant();}
 async Task ValidateRefs(SaveTransferParametersRequest r,CancellationToken ct){if(r.BranchId.HasValue&&!await db.Branches.AnyAsync(x=>x.Id==r.BranchId&&x.IsActive,ct))throw new ArgumentException("Selected branch is not active.");if(r.WarehouseId.HasValue&&!await db.Warehouses.AnyAsync(x=>x.Id==r.WarehouseId&&x.IsActive&&(!r.BranchId.HasValue||x.BranchId==r.BranchId),ct))throw new ArgumentException("Selected warehouse is not active or does not belong to the selected branch.");if(r.DefaultInventoryStatusId.HasValue&&!await db.InventoryStatuses.AnyAsync(x=>x.Id==r.DefaultInventoryStatusId&&x.IsActive,ct))throw new ArgumentException("Selected inventory status is not active.");}
 static void Validate(SaveTransferParametersRequest r){if(!Token.IsMatch(r.Format))throw new ArgumentException("Format must contain a {NUMBER} or {NUMBER:n} token.");if(r.Format.Length>120||Format(r.Format,r.NextNumber,"0").Length>40)throw new ArgumentException("Generated transfer number cannot exceed 40 characters.");if(r.IncrementBy<1||r.MinimumNumber<0||r.NextNumber<r.MinimumNumber||r.MaximumNumber<r.NextNumber)throw new ArgumentException("Number range values are invalid.");if(r.DefaultTransitDays is <0 or >3650||r.MaximumLinesPerTransfer is <1 or >10000)throw new ArgumentException("Transfer parameter limits are invalid.");if(string.IsNullOrWhiteSpace(r.InventoryCurrencyCode)||r.InventoryCurrencyCode.Trim().Length!=3)throw new ArgumentException("Inventory currency must be a three-letter ISO code.");if(r.AutoConfirmOnCreate&&!r.RequireConfirmationBeforeShipment)throw new ArgumentException("Automatic confirmation requires confirmation control to be enabled.");}
 async Task<long>Consume(NumberSequence s,CancellationToken ct){if(s.Id==0){db.Add(s);await db.SaveChangesAsync(ct);}var c=db.Database.GetDbConnection();if(c.State!=ConnectionState.Open)await c.OpenAsync(ct);await using var cmd=c.CreateCommand();cmd.Transaction=db.Database.CurrentTransaction?.GetDbTransaction();cmd.CommandText="UPDATE RII_NUMBER_SEQUENCES WITH (UPDLOCK, ROWLOCK) SET CurrentNumber=CurrentNumber+IncrementBy,UpdatedAt=SYSUTCDATETIME() OUTPUT DELETED.CurrentNumber WHERE Id=@id AND IsActive=1 AND CurrentNumber<=MaximumNumber";var p=cmd.CreateParameter();p.ParameterName="@id";p.Value=s.Id;cmd.Parameters.Add(p);var v=await cmd.ExecuteScalarAsync(ct);return v is null||v==DBNull.Value?throw new InvalidOperationException("Transfer number sequence could not be consumed."):Convert.ToInt64(v);}
 static string Format(string f,long n,string branch){var result=f.Replace("{BRANCH}",branch,StringComparison.OrdinalIgnoreCase).Replace("{YYYY}",DateTime.UtcNow.ToString("yyyy"),StringComparison.OrdinalIgnoreCase).Replace("{YY}",DateTime.UtcNow.ToString("yy"),StringComparison.OrdinalIgnoreCase).Replace("{MM}",DateTime.UtcNow.ToString("MM"),StringComparison.OrdinalIgnoreCase);return Token.Replace(result,m=>n.ToString().PadLeft(Math.Clamp(int.TryParse(m.Groups["length"].Value,out var l)?l:1,1,18),'0'));}
}
