using System.Data;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using verii_metivon_api.Core.Persistence;
using verii_metivon_api.Modules.Parameters.Domain.Entities;
using verii_metivon_api.Modules.Receiving.Domain.Entities;

namespace verii_metivon_api.Modules.Receiving.Application.Parameters;

public sealed record ReceivingParametersDto(long? BranchId,long? WarehouseId,bool IsAutomatic,bool AllowManual,string Format,long NextNumber,int IncrementBy,long MinimumNumber,long MaximumNumber,bool IsContinuous,bool RequirePurchaseOrder,bool AllowFreeReceipt,bool AllowPartialReceipt,decimal OverDeliveryTolerancePercent,decimal UnderDeliveryTolerancePercent,bool RequireSupplierDeliveryNoteNumber,bool RequireLotNumberForLotTracked,bool RequireSerialsForSerialTracked,bool RequireExpiryDateForTrackedItems,int MinimumRemainingShelfLifeDays,bool RequireQualityInspection,bool AutoCreateLabels,int DefaultLabelCopies,string InventoryCurrencyCode,string Preview);
public sealed record SaveReceivingParametersRequest(long? BranchId,long? WarehouseId,bool IsAutomatic,bool AllowManual,string Format,long NextNumber,int IncrementBy,long MinimumNumber,long MaximumNumber,bool IsContinuous,bool RequirePurchaseOrder,bool AllowFreeReceipt,bool AllowPartialReceipt,decimal OverDeliveryTolerancePercent,decimal UnderDeliveryTolerancePercent,bool RequireSupplierDeliveryNoteNumber,bool RequireLotNumberForLotTracked,bool RequireSerialsForSerialTracked,bool RequireExpiryDateForTrackedItems,int MinimumRemainingShelfLifeDays,bool RequireQualityInspection,bool AutoCreateLabels,int DefaultLabelCopies,string InventoryCurrencyCode);

public interface IReceivingParameterService
{
    Task<ReceivingParametersDto>GetAsync(long? branchId,long? warehouseId,CancellationToken ct);
    Task<ReceivingParametersDto>SaveAsync(SaveReceivingParametersRequest request,CancellationToken ct);
    Task<ReceivingParameterSettings>ResolveSettingsAsync(long? branchId,long? warehouseId,CancellationToken ct);
    Task<string>ResolveNumberAsync(string? requestedNumber,long? branchId,CancellationToken ct);
}

public sealed class ReceivingParameterService(MetivonDbContext db):IReceivingParameterService
{
    private const string Module="Receiving";private const string Reference="GoodsReceiptNumber";
    private static readonly Regex NumberToken=new(@"\{NUMBER(?::(?<length>\d{1,2}))?\}",RegexOptions.Compiled|RegexOptions.IgnoreCase);
    public async Task<ReceivingParametersDto>GetAsync(long? branchId,long? warehouseId,CancellationToken ct)
    {var s=await ResolveSequence(branchId,ct);var p=await ResolveSettingsAsync(branchId,warehouseId,ct);var branch=await BranchCode(branchId,ct);return Map(s,p,branch,warehouseId);}
    public async Task<ReceivingParametersDto>SaveAsync(SaveReceivingParametersRequest r,CancellationToken ct)
    {
        Validate(r);await ValidateReferences(r,ct);await using var transaction=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);
        var s=await db.NumberSequences.FirstOrDefaultAsync(x=>x.Module==Module&&x.Reference==Reference&&x.BranchId==r.BranchId,ct);
        if(s is null){s=new NumberSequence{Module=Module,Reference=Reference,BranchId=r.BranchId};db.Add(s);}s.Format=r.Format.Trim();s.CurrentNumber=r.NextNumber;s.IncrementBy=r.IncrementBy;s.MinimumNumber=r.MinimumNumber;s.MaximumNumber=r.MaximumNumber;s.IsAutomatic=r.IsAutomatic;s.AllowManual=r.AllowManual;s.IsContinuous=r.IsContinuous;s.IsActive=true;
        var p=await db.ReceivingParameterSettings.FirstOrDefaultAsync(x=>x.BranchId==r.BranchId&&x.WarehouseId==r.WarehouseId,ct);
        if(p is null){p=new ReceivingParameterSettings{BranchId=r.BranchId,WarehouseId=r.WarehouseId};db.Add(p);}Apply(p,r);
        await db.SaveChangesAsync(ct);await transaction.CommitAsync(ct);return await GetAsync(r.BranchId,r.WarehouseId,ct);
    }
    public async Task<ReceivingParameterSettings>ResolveSettingsAsync(long? branchId,long? warehouseId,CancellationToken ct)=>await db.ReceivingParameterSettings.AsNoTracking().Where(x=>(x.BranchId==branchId||x.BranchId==null)&&(x.WarehouseId==warehouseId||x.WarehouseId==null)).OrderByDescending(x=>x.WarehouseId.HasValue).ThenByDescending(x=>x.BranchId.HasValue).FirstOrDefaultAsync(ct)??new ReceivingParameterSettings{BranchId=branchId,WarehouseId=warehouseId};
    public async Task<string>ResolveNumberAsync(string? requestedNumber,long? branchId,CancellationToken ct)
    {var s=await ResolveSequence(branchId,ct);var manual=requestedNumber?.Trim().ToUpperInvariant();if(!string.IsNullOrWhiteSpace(manual)){if(s.IsAutomatic&&!s.AllowManual)throw new InvalidOperationException("Manual goods receipt number is not allowed by receiving parameters.");return manual;}if(!s.IsAutomatic)throw new InvalidOperationException("Goods receipt number is required because automatic numbering is disabled.");return Format(s.Format,await Consume(s,ct),await BranchCode(branchId,ct));}
    private async Task<NumberSequence>ResolveSequence(long? branchId,CancellationToken ct)=>await db.NumberSequences.AsNoTracking().Where(x=>x.Module==Module&&x.Reference==Reference&&x.IsActive&&(x.BranchId==branchId||x.BranchId==null)).OrderByDescending(x=>x.BranchId.HasValue).FirstOrDefaultAsync(ct)??new NumberSequence{Module=Module,Reference=Reference,BranchId=branchId,Format="GR-{YYYY}-{NUMBER:6}",CurrentNumber=1,IncrementBy=1,MinimumNumber=1,MaximumNumber=999999999,IsAutomatic=true,AllowManual=true};
    private async Task<string>BranchCode(long? id,CancellationToken ct)=>id.HasValue?await db.Branches.AsNoTracking().Where(x=>x.Id==id).Select(x=>x.Code).FirstOrDefaultAsync(ct)??"0":"0";
    private static ReceivingParametersDto Map(NumberSequence s,ReceivingParameterSettings p,string branch,long? warehouseId)=>new(s.BranchId,warehouseId,s.IsAutomatic,s.AllowManual,s.Format,s.CurrentNumber,s.IncrementBy,s.MinimumNumber,s.MaximumNumber,s.IsContinuous,p.RequirePurchaseOrder,p.AllowFreeReceipt,p.AllowPartialReceipt,p.OverDeliveryTolerancePercent,p.UnderDeliveryTolerancePercent,p.RequireSupplierDeliveryNoteNumber,p.RequireLotNumberForLotTracked,p.RequireSerialsForSerialTracked,p.RequireExpiryDateForTrackedItems,p.MinimumRemainingShelfLifeDays,p.RequireQualityInspection,p.AutoCreateLabels,p.DefaultLabelCopies,p.InventoryCurrencyCode,Format(s.Format,s.CurrentNumber,branch));
    private static void Apply(ReceivingParameterSettings p,SaveReceivingParametersRequest r){p.RequirePurchaseOrder=r.RequirePurchaseOrder;p.AllowFreeReceipt=r.AllowFreeReceipt;p.AllowPartialReceipt=r.AllowPartialReceipt;p.OverDeliveryTolerancePercent=r.OverDeliveryTolerancePercent;p.UnderDeliveryTolerancePercent=r.UnderDeliveryTolerancePercent;p.RequireSupplierDeliveryNoteNumber=r.RequireSupplierDeliveryNoteNumber;p.RequireLotNumberForLotTracked=r.RequireLotNumberForLotTracked;p.RequireSerialsForSerialTracked=r.RequireSerialsForSerialTracked;p.RequireExpiryDateForTrackedItems=r.RequireExpiryDateForTrackedItems;p.MinimumRemainingShelfLifeDays=r.MinimumRemainingShelfLifeDays;p.RequireQualityInspection=r.RequireQualityInspection;p.AutoCreateLabels=r.AutoCreateLabels;p.DefaultLabelCopies=r.DefaultLabelCopies;p.InventoryCurrencyCode=r.InventoryCurrencyCode.Trim().ToUpperInvariant();}
    private async Task ValidateReferences(SaveReceivingParametersRequest r,CancellationToken ct){if(r.BranchId.HasValue&&!await db.Branches.AnyAsync(x=>x.Id==r.BranchId&&x.IsActive,ct))throw new ArgumentException("Selected branch is not active.");if(r.WarehouseId.HasValue&&!await db.Warehouses.AnyAsync(x=>x.Id==r.WarehouseId&&x.IsActive&&(!r.BranchId.HasValue||x.BranchId==r.BranchId),ct))throw new ArgumentException("Selected warehouse is not active or does not belong to the selected branch.");}
    private static void Validate(SaveReceivingParametersRequest r){if(!NumberToken.IsMatch(r.Format))throw new ArgumentException("Format must contain a {NUMBER} or {NUMBER:n} token.");if(r.Format.Length>120||Format(r.Format,r.NextNumber,"0").Length>40)throw new ArgumentException("Generated goods receipt number cannot exceed 40 characters.");if(r.IncrementBy<1||r.MinimumNumber<0||r.NextNumber<r.MinimumNumber||r.MaximumNumber<r.NextNumber)throw new ArgumentException("Number range values are invalid.");if(r.OverDeliveryTolerancePercent is <0 or >100||r.UnderDeliveryTolerancePercent is <0 or >100||r.MinimumRemainingShelfLifeDays<0||r.DefaultLabelCopies is <1 or >100)throw new ArgumentException("One or more receiving parameter values are invalid.");if(string.IsNullOrWhiteSpace(r.InventoryCurrencyCode)||r.InventoryCurrencyCode.Trim().Length!=3)throw new ArgumentException("Inventory currency must be a three-letter ISO code.");}
    private async Task<long>Consume(NumberSequence s,CancellationToken ct){if(s.Id==0){db.Add(s);await db.SaveChangesAsync(ct);}if(s.CurrentNumber>s.MaximumNumber)throw new InvalidOperationException("Goods receipt number sequence is exhausted.");var c=db.Database.GetDbConnection();if(c.State!=ConnectionState.Open)await c.OpenAsync(ct);await using var command=c.CreateCommand();command.Transaction=db.Database.CurrentTransaction?.GetDbTransaction();command.CommandText="UPDATE RII_NUMBER_SEQUENCES WITH (UPDLOCK, ROWLOCK) SET CurrentNumber = CurrentNumber + IncrementBy, UpdatedAt = SYSUTCDATETIME() OUTPUT DELETED.CurrentNumber WHERE Id = @id AND IsActive = 1 AND CurrentNumber <= MaximumNumber";var p=command.CreateParameter();p.ParameterName="@id";p.Value=s.Id;command.Parameters.Add(p);var result=await command.ExecuteScalarAsync(ct);return result is null||result==DBNull.Value?throw new InvalidOperationException("Goods receipt number sequence could not be consumed."):Convert.ToInt64(result);}
    private static string Format(string format,long number,string branch){var result=format.Replace("{BRANCH}",branch,StringComparison.OrdinalIgnoreCase).Replace("{YYYY}",DateTime.UtcNow.ToString("yyyy"),StringComparison.OrdinalIgnoreCase).Replace("{YY}",DateTime.UtcNow.ToString("yy"),StringComparison.OrdinalIgnoreCase).Replace("{MM}",DateTime.UtcNow.ToString("MM"),StringComparison.OrdinalIgnoreCase);return NumberToken.Replace(result,m=>number.ToString().PadLeft(Math.Clamp(int.TryParse(m.Groups["length"].Value,out var length)?length:1,1,18),'0'));}
}
