using Microsoft.EntityFrameworkCore;
using verii_metivon_api.Core.Persistence;
using verii_metivon_api.Modules.Warehouses.Domain.Entities;

namespace verii_metivon_api.Modules.Warehouses.Application.Parameters;

public sealed record WarehouseParametersDto(long? BranchId,long? WarehouseId,bool AllowNegativeStockByDefault,bool RequireLocation,long? DefaultReceivingLocationId,long? DefaultQuarantineLocationId,long? DefaultShippingLocationId,bool UseDirectedPutAway,bool UseDirectedPicking,bool CheckCapacity,string LocationCodeFormat,int DefaultLabelCopies,string LocationCodePreview);
public sealed record SaveWarehouseParametersRequest(long? BranchId,long? WarehouseId,bool AllowNegativeStockByDefault,bool RequireLocation,long? DefaultReceivingLocationId,long? DefaultQuarantineLocationId,long? DefaultShippingLocationId,bool UseDirectedPutAway,bool UseDirectedPicking,bool CheckCapacity,string LocationCodeFormat,int DefaultLabelCopies);
public interface IWarehouseParameterService{Task<WarehouseParametersDto>GetAsync(long? branchId,long? warehouseId,CancellationToken ct);Task<WarehouseParametersDto>SaveAsync(SaveWarehouseParametersRequest request,CancellationToken ct);}

public sealed class WarehouseParameterService(MetivonDbContext db):IWarehouseParameterService
{
    public async Task<WarehouseParametersDto>GetAsync(long? branchId,long? warehouseId,CancellationToken ct){var p=await Resolve(branchId,warehouseId,ct);var warehouseCode=warehouseId.HasValue?await db.Warehouses.AsNoTracking().Where(x=>x.Id==warehouseId).Select(x=>x.Code).FirstOrDefaultAsync(ct)??"WH":"WH";return Map(p,branchId,warehouseId,warehouseCode);}
    public async Task<WarehouseParametersDto>SaveAsync(SaveWarehouseParametersRequest r,CancellationToken ct){Validate(r);await ValidateReferences(r,ct);var p=await db.WarehouseParameterSettings.FirstOrDefaultAsync(x=>x.BranchId==r.BranchId&&x.WarehouseId==r.WarehouseId,ct);if(p is null){p=new WarehouseParameterSettings{BranchId=r.BranchId,WarehouseId=r.WarehouseId};db.Add(p);}p.AllowNegativeStockByDefault=r.AllowNegativeStockByDefault;p.RequireLocation=r.RequireLocation;p.DefaultReceivingLocationId=r.DefaultReceivingLocationId;p.DefaultQuarantineLocationId=r.DefaultQuarantineLocationId;p.DefaultShippingLocationId=r.DefaultShippingLocationId;p.UseDirectedPutAway=r.UseDirectedPutAway;p.UseDirectedPicking=r.UseDirectedPicking;p.CheckCapacity=r.CheckCapacity;p.LocationCodeFormat=r.LocationCodeFormat.Trim();p.DefaultLabelCopies=r.DefaultLabelCopies;await db.SaveChangesAsync(ct);return await GetAsync(r.BranchId,r.WarehouseId,ct);}
    private async Task<WarehouseParameterSettings>Resolve(long? branchId,long? warehouseId,CancellationToken ct)=>await db.WarehouseParameterSettings.AsNoTracking().Where(x=>(x.BranchId==null||x.BranchId==branchId)&&(x.WarehouseId==null||x.WarehouseId==warehouseId)).OrderByDescending(x=>x.WarehouseId.HasValue).ThenByDescending(x=>x.BranchId.HasValue).FirstOrDefaultAsync(ct)??new WarehouseParameterSettings{BranchId=branchId,WarehouseId=warehouseId};
    private static WarehouseParametersDto Map(WarehouseParameterSettings p,long? branchId,long? warehouseId,string warehouseCode)=>new(branchId,warehouseId,p.AllowNegativeStockByDefault,p.RequireLocation,p.DefaultReceivingLocationId,p.DefaultQuarantineLocationId,p.DefaultShippingLocationId,p.UseDirectedPutAway,p.UseDirectedPicking,p.CheckCapacity,p.LocationCodeFormat,p.DefaultLabelCopies,p.LocationCodeFormat.Replace("{WAREHOUSE}",warehouseCode,StringComparison.OrdinalIgnoreCase).Replace("{AISLE}","A01",StringComparison.OrdinalIgnoreCase).Replace("{RACK}","R01",StringComparison.OrdinalIgnoreCase).Replace("{BIN}","B01",StringComparison.OrdinalIgnoreCase));
    private async Task ValidateReferences(SaveWarehouseParametersRequest r,CancellationToken ct){if(r.BranchId.HasValue&&!await db.Branches.AnyAsync(x=>x.Id==r.BranchId&&x.IsActive,ct))throw new ArgumentException("Selected branch is not active.");if(r.WarehouseId.HasValue&&!await db.Warehouses.AnyAsync(x=>x.Id==r.WarehouseId&&x.IsActive&&(!r.BranchId.HasValue||x.BranchId==r.BranchId),ct))throw new ArgumentException("Selected warehouse is not active or does not belong to the branch.");var ids=new[]{r.DefaultReceivingLocationId,r.DefaultQuarantineLocationId,r.DefaultShippingLocationId}.Where(x=>x.HasValue).Select(x=>x!.Value).Distinct().ToArray();if(ids.Length>0){if(!r.WarehouseId.HasValue)throw new ArgumentException("Warehouse scope is required when default locations are selected.");var count=await db.StorageLocations.CountAsync(x=>ids.Contains(x.Id)&&x.WarehouseId==r.WarehouseId&&x.IsActive&&!x.IsBlocked,ct);if(count!=ids.Length)throw new ArgumentException("One or more default locations are invalid, blocked, or belong to another warehouse.");}}
    private static void Validate(SaveWarehouseParametersRequest r){if(string.IsNullOrWhiteSpace(r.LocationCodeFormat)||r.LocationCodeFormat.Length>160)throw new ArgumentException("Location code format is required and cannot exceed 160 characters.");if(!r.LocationCodeFormat.Contains("{WAREHOUSE}",StringComparison.OrdinalIgnoreCase))throw new ArgumentException("Location code format must contain {WAREHOUSE}.");if(r.DefaultLabelCopies is<1 or>100)throw new ArgumentException("Default label copies must be between 1 and 100.");}
}
