using verii_metivon_api.Core.Domain;using verii_metivon_api.Modules.Procurement.Domain.Enums;using verii_metivon_api.Modules.Products.Domain.Entities;using verii_metivon_api.Modules.Warehouses.Domain.Entities;
namespace verii_metivon_api.Modules.Procurement.Domain.Entities;
public sealed class PurchaseOrder:Entity{public string OrderNumber{get;set;}=string.Empty;public PurchaseOrderType OrderType{get;set;}public PurchaseOrderStatus Status{get;set;}public long BranchId{get;set;}public Branch Branch{get;set;}=null!;public long SupplierId{get;set;}public BusinessPartner Supplier{get;set;}=null!;public long CurrencyId{get;set;}public Currency Currency{get;set;}=null!;public long PaymentTermId{get;set;}public PaymentTerm PaymentTerm{get;set;}=null!;public long WarehouseId{get;set;}public Warehouse Warehouse{get;set;}=null!;public DateOnly OrderDate{get;set;}public DateOnly? RequestedDeliveryDate{get;set;}public DateOnly? ConfirmedDeliveryDate{get;set;}public string? SupplierReference{get;set;}public string? BuyerNote{get;set;}public decimal ExchangeRate{get;set;}=1;public decimal Subtotal{get;set;}public decimal DiscountTotal{get;set;}public decimal TaxTotal{get;set;}public decimal GrandTotal{get;set;}public DateTime? ConfirmedAt{get;set;}public long? ConfirmedBy{get;set;}public ICollection<PurchaseOrderLine> Lines{get;set;}=new List<PurchaseOrderLine>();}
public sealed class PurchaseOrderLine:Entity{public long PurchaseOrderId{get;set;}public PurchaseOrder PurchaseOrder{get;set;}=null!;public int LineNumber{get;set;}public long ProductId{get;set;}public Product Product{get;set;}=null!;public long UnitId{get;set;}public Unit Unit{get;set;}=null!;public long? StorageLocationId{get;set;}public StorageLocation? StorageLocation{get;set;}public PurchaseLineStatus Status{get;set;}public string? Description{get;set;}public decimal OrderedQuantity{get;set;}public decimal ReceivedQuantity{get;set;}public decimal InvoicedQuantity{get;set;}public decimal UnitPrice{get;set;}public decimal DiscountRate{get;set;}public decimal DiscountAmount{get;set;}public decimal TaxRate{get;set;}public decimal TaxAmount{get;set;}public decimal LineTotal{get;set;}public DateOnly? RequestedDeliveryDate{get;set;}public decimal OverDeliveryTolerance{get;set;}public decimal UnderDeliveryTolerance{get;set;}public bool IsClosed{get;set;}}
public sealed class ProcurementParameterSettings:Entity
{
 public long?BranchId{get;set;}public Branch?Branch{get;set;}public long?WarehouseId{get;set;}public Warehouse?Warehouse{get;set;}
 public bool RequireApprovalBeforeConfirmation{get;set;}public bool AutoApproveOnCreate{get;set;}public bool RequireRequestedDeliveryDate{get;set;}=true;public int DefaultLeadTimeDays{get;set;}=7;public bool AllowPastOrderDate{get;set;}
 public bool RequireSupplierReference{get;set;}public bool RequireBuyerNote{get;set;}public decimal DefaultOverDeliveryTolerancePercent{get;set;}public decimal DefaultUnderDeliveryTolerancePercent{get;set;}
 public decimal MinimumOrderAmount{get;set;}public decimal MaximumOrderAmount{get;set;}public int MaximumLinesPerOrder{get;set;}=200;public bool AllowZeroPrice{get;set;}public bool AllowDiscount{get;set;}=true;public decimal MaximumDiscountPercent{get;set;}=100;public bool RequireActiveSupplier{get;set;}=true;
 public byte[]RowVersion{get;set;}=[];
}
