using Microsoft.EntityFrameworkCore;using verii_metivon_api.Core.Auth;using verii_metivon_api.Core.Paging;using verii_metivon_api.Core.Persistence;using verii_metivon_api.Core.UnitOfWork;using verii_metivon_api.Modules.Inventory.Application.Services;using verii_metivon_api.Modules.Inventory.Domain.Enums;using verii_metivon_api.Modules.Products.Domain.Enums;using verii_metivon_api.Modules.Transfers.Application.Parameters;using verii_metivon_api.Modules.Transfers.Domain.Entities;
using verii_metivon_api.Modules.NumberSeries.Application;
namespace verii_metivon_api.Modules.Transfers.Application.Services;
public sealed class TransferOrderQuery:PagedQuery{public long?WarehouseId{get;init;}public TransferOrderStatus?Status{get;init;}}
public sealed record TransferOrderRow(long Id,string TransferNumber,string FromWarehouse,string ToWarehouse,DateOnly TransferDate,DateOnly?ExpectedReceiptDate,string Status);
public sealed record CreateTransferLine(long ProductId,long UnitId,long FromLocationId,long ToLocationId,long?InventoryStatusId,long?InventoryLotId,long?InventorySerialId,IReadOnlyList<long>?InventorySerialIds,decimal Quantity,string?Notes);
public sealed record CreateTransferRequest(string?TransferNumber,long?NumberSeriesId,long FromWarehouseId,long ToWarehouseId,DateOnly TransferDate,DateOnly?ExpectedReceiptDate,string?Notes,IReadOnlyList<CreateTransferLine>Lines);
public interface ITransferOrderService{Task<ApiResponse<PagedResult<TransferOrderRow>>>GetPagedAsync(TransferOrderQuery q,CancellationToken ct);Task<ApiResponse<object>>CreateAsync(CreateTransferRequest r,CancellationToken ct);Task<ApiResponse<object>>ShipAsync(long id,CancellationToken ct);Task<ApiResponse<object>>ReceiveAsync(long id,CancellationToken ct);}
public sealed class TransferOrderService(IUnitOfWork u,IInventoryService inventory,ITransferParameterService parameters,MetivonDbContext db,INumberSeriesService numberSeries):ITransferOrderService
{
 public async Task<ApiResponse<PagedResult<TransferOrderRow>>>GetPagedAsync(TransferOrderQuery q,CancellationToken ct){var x=u.Repository<TransferOrder>().Query().Include(v=>v.FromWarehouse).Include(v=>v.ToWarehouse).AsQueryable();if(q.WarehouseId.HasValue)x=x.Where(v=>v.FromWarehouseId==q.WarehouseId||v.ToWarehouseId==q.WarehouseId);if(q.Status.HasValue)x=x.Where(v=>v.Status==q.Status);if(!string.IsNullOrWhiteSpace(q.Search)){var s=q.Search.Trim();x=x.Where(v=>v.TransferNumber.Contains(s));}x=x.ApplyPagedFilters(q);var total=await x.CountAsync(ct);var rows=await x.OrderByDescending(v=>v.TransferDate).Skip((q.NormalizedPageNumber-1)*q.NormalizedPageSize).Take(q.NormalizedPageSize).Select(v=>new TransferOrderRow(v.Id,v.TransferNumber,v.FromWarehouse.Code,v.ToWarehouse.Code,v.TransferDate,v.ExpectedReceiptDate,v.Status.ToString())).ToListAsync(ct);return ApiResponse<PagedResult<TransferOrderRow>>.Ok(new(rows,q.NormalizedPageNumber,q.NormalizedPageSize,total));}
 public async Task<ApiResponse<object>>CreateAsync(CreateTransferRequest r,CancellationToken ct)
 {
  if(r.FromWarehouseId==r.ToWarehouseId||r.Lines.Count==0)return ApiResponse<object>.Error("Different warehouses and lines are required.",400);
  var from=await db.Warehouses.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==r.FromWarehouseId&&x.IsActive,ct);var to=await db.Warehouses.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==r.ToWarehouseId&&x.IsActive,ct);if(from is null||to is null)return ApiResponse<object>.Error("Source and destination warehouses must be active.",400);
  var p=await parameters.ResolveSettingsAsync(from.BranchId,from.Id,ct);var today=DateOnly.FromDateTime(DateTime.UtcNow);
  if(!p.AllowCrossBranchTransfer&&from.BranchId!=to.BranchId)return ApiResponse<object>.Error("Cross-branch transfers are disabled by transfer parameters.",400);if(!p.AllowPastTransferDate&&r.TransferDate<today)return ApiResponse<object>.Error("Past transfer dates are disabled.",400);if(p.RequireNotes&&string.IsNullOrWhiteSpace(r.Notes))return ApiResponse<object>.Error("Transfer notes are required.",400);if(r.Lines.Count>p.MaximumLinesPerTransfer)return ApiResponse<object>.Error($"A transfer can contain at most {p.MaximumLinesPerTransfer} lines.",400);
  if(p.RequireExpectedReceiptDate&&!r.ExpectedReceiptDate.HasValue&&p.DefaultTransitDays==0)return ApiResponse<object>.Error("Expected receipt date is required.",400);var expected=r.ExpectedReceiptDate??r.TransferDate.AddDays(p.DefaultTransitDays);if(expected<r.TransferDate)return ApiResponse<object>.Error("Expected receipt date cannot be before transfer date.",400);
  ReservedNumber? reserved=null;var transferNumber=r.TransferNumber?.Trim();if(string.IsNullOrWhiteSpace(transferNumber)){reserved=await numberSeries.ReserveAsync(new("Transfers","TransferNumber",r.NumberSeriesId,from.BranchId,from.Id,null,null,null,null,r.TransferDate,"TransferOrder"),ct);transferNumber=reserved.DocumentNumber;}else transferNumber=await parameters.ResolveNumberAsync(transferNumber,from.BranchId,ct);var e=new TransferOrder{TransferNumber=transferNumber,Status=p.AutoConfirmOnCreate?TransferOrderStatus.Confirmed:TransferOrderStatus.Draft,FromWarehouseId=r.FromWarehouseId,ToWarehouseId=r.ToWarehouseId,TransferDate=r.TransferDate,ExpectedReceiptDate=expected,Notes=r.Notes?.Trim()};var n=0;
  foreach(var l in r.Lines)
  {
   if(l.Quantity<=0)return ApiResponse<object>.Error("Transfer quantity must be greater than zero.",400);var fromLocation=await db.StorageLocations.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==l.FromLocationId&&x.IsActive&&!x.IsBlocked,ct);var toLocation=await db.StorageLocations.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==l.ToLocationId&&x.IsActive&&!x.IsBlocked,ct);if(fromLocation?.WarehouseId!=from.Id||toLocation?.WarehouseId!=to.Id)return ApiResponse<object>.Error("Transfer locations must belong to their selected warehouses and be active.",400);
   var product=await db.Products.AsNoTracking().Where(x=>x.Id==l.ProductId&&x.IsActive).Select(x=>new{x.TrackingType}).FirstOrDefaultAsync(ct);if(product is null)return ApiResponse<object>.Error("Transfer product is not active.",400);if(product.TrackingType==InventoryTrackingType.Lot&&p.RequireLotForLotTracked&&!l.InventoryLotId.HasValue)return ApiResponse<object>.Error("Lot is required for lot-tracked products.",400);
   var serialIds=(l.InventorySerialIds??Array.Empty<long>()).Append(l.InventorySerialId??0).Where(x=>x>0).Distinct().ToArray();
   if(product.TrackingType==InventoryTrackingType.Serial&&(p.RequireSerialForSerialTracked&&serialIds.Length==0||l.Quantity!=serialIds.Length))return ApiResponse<object>.Error("Selected serial count must match transfer quantity.",400);
   if(product.TrackingType!=InventoryTrackingType.Serial&&serialIds.Length>0)return ApiResponse<object>.Error("Serials can only be selected for serial-tracked products.",400);
   if(serialIds.Length>0&&await db.InventorySerials.CountAsync(x=>serialIds.Contains(x.Id)&&x.ProductId==l.ProductId&&x.IsActive,ct)!=serialIds.Length)return ApiResponse<object>.Error("One or more selected serials do not belong to the transfer product.",400);
   var statusId=l.InventoryStatusId??p.DefaultInventoryStatusId;if(!statusId.HasValue)return ApiResponse<object>.Error("Inventory status is required because no default is configured.",400);if(!await db.InventoryStatuses.AnyAsync(x=>x.Id==statusId&&x.IsActive,ct))return ApiResponse<object>.Error("Inventory status is not active.",400);
   if(serialIds.Length>0){foreach(var serialId in serialIds)e.Lines.Add(new TransferOrderLine{LineNumber=++n,ProductId=l.ProductId,UnitId=l.UnitId,FromLocationId=l.FromLocationId,ToLocationId=l.ToLocationId,InventoryStatusId=statusId.Value,InventoryLotId=l.InventoryLotId,InventorySerialId=serialId,RequestedQuantity=1,Notes=l.Notes});}
   else e.Lines.Add(new TransferOrderLine{LineNumber=++n,ProductId=l.ProductId,UnitId=l.UnitId,FromLocationId=l.FromLocationId,ToLocationId=l.ToLocationId,InventoryStatusId=statusId.Value,InventoryLotId=l.InventoryLotId,InventorySerialId=null,RequestedQuantity=l.Quantity,Notes=l.Notes});
  }
  await u.Repository<TransferOrder>().AddAsync(e,ct);await u.SaveChangesAsync(ct);if(reserved is not null)await numberSeries.MarkUsedAsync(reserved.UsageId,e.Id,ct);return ApiResponse<object>.Ok(new{e.Id,e.TransferNumber,e.Status,e.ExpectedReceiptDate,NumberSeriesUsageId=reserved?.UsageId});
 }
 public async Task<ApiResponse<object>>ShipAsync(long id,CancellationToken ct){var e=await Load(id,ct);if(e is null)return ApiResponse<object>.Error("Transfer not found.",404);var branchId=await db.Warehouses.AsNoTracking().Where(x=>x.Id==e.FromWarehouseId).Select(x=>x.BranchId).FirstAsync(ct);var p=await parameters.ResolveSettingsAsync(branchId,e.FromWarehouseId,ct);if(p.RequireConfirmationBeforeShipment&&e.Status!=TransferOrderStatus.Confirmed)return ApiResponse<object>.Error("Transfer must be confirmed before shipment.",409);if(!p.RequireConfirmationBeforeShipment&&e.Status is not(TransferOrderStatus.Draft or TransferOrderStatus.Confirmed))return ApiResponse<object>.Error("Transfer is not shippable.",409);await u.ExecuteInTransactionAsync(async t=>{var lines=e.Lines.Select(x=>new PostInventoryLine(x.ProductId,x.UnitId,e.FromWarehouseId,x.FromLocationId,x.InventoryStatusId,x.InventoryLotId,x.InventorySerialId,x.RequestedQuantity,null,x.Id,x.Notes)).ToList();var posting=await inventory.PostAsync(new($"TRANSFER-ISSUE:{e.Id}","TransferOrder",e.Id,e.TransferNumber,DateTime.UtcNow,InventoryMovementType.TransferIssue,InventoryMovementDirection.Issue,p.InventoryCurrencyCode,lines),t);if(!posting.Success)throw new InvalidOperationException(posting.Message);e.IssuePostingId=posting.Data!.PostingId;e.Status=TransferOrderStatus.Shipped;e.ShippedAt=DateTime.UtcNow;e.Lines.ToList().ForEach(x=>x.ShippedQuantity=x.RequestedQuantity);await u.SaveChangesAsync(t);},ct);return ApiResponse<object>.Ok(new{e.Id,e.IssuePostingId});}
 public async Task<ApiResponse<object>>ReceiveAsync(long id,CancellationToken ct){var e=await Load(id,ct);if(e is null)return ApiResponse<object>.Error("Transfer not found.",404);if(e.Status!=TransferOrderStatus.Shipped)return ApiResponse<object>.Error("Only shipped transfers can be received.",409);var branchId=await db.Warehouses.AsNoTracking().Where(x=>x.Id==e.FromWarehouseId).Select(x=>x.BranchId).FirstAsync(ct);var p=await parameters.ResolveSettingsAsync(branchId,e.FromWarehouseId,ct);if(!p.AllowReceiptBeforeExpectedDate&&e.ExpectedReceiptDate>DateOnly.FromDateTime(DateTime.UtcNow))return ApiResponse<object>.Error("Receipt before the expected date is disabled.",409);await u.ExecuteInTransactionAsync(async t=>{var lines=e.Lines.Select(x=>new PostInventoryLine(x.ProductId,x.UnitId,e.ToWarehouseId,x.ToLocationId,x.InventoryStatusId,x.InventoryLotId,x.InventorySerialId,x.ShippedQuantity,null,x.Id,x.Notes)).ToList();var posting=await inventory.PostAsync(new($"TRANSFER-RECEIPT:{e.Id}","TransferOrder",e.Id,e.TransferNumber,DateTime.UtcNow,InventoryMovementType.TransferReceipt,InventoryMovementDirection.Receipt,p.InventoryCurrencyCode,lines),t);if(!posting.Success)throw new InvalidOperationException(posting.Message);e.ReceiptPostingId=posting.Data!.PostingId;e.Status=TransferOrderStatus.Received;e.ReceivedAt=DateTime.UtcNow;e.Lines.ToList().ForEach(x=>x.ReceivedQuantity=x.ShippedQuantity);await u.SaveChangesAsync(t);},ct);return ApiResponse<object>.Ok(new{e.Id,e.ReceiptPostingId});}
 Task<TransferOrder?>Load(long id,CancellationToken ct)=>u.Repository<TransferOrder>().Query(true).Include(x=>x.Lines).FirstOrDefaultAsync(x=>x.Id==id,ct);
}


