using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using verii_metivon_api.Core.Auth;
using verii_metivon_api.Core.Domain;
using verii_metivon_api.Core.Paging;
using verii_metivon_api.Core.UnitOfWork;
using verii_metivon_api.Modules.Accounting.Application.Parameters;
using verii_metivon_api.Modules.Accounting.Domain.Entities;

namespace verii_metivon_api.Modules.Accounting.Application.Services;
public sealed class LedgerAccountQuery:PagedQuery{public AccountType?AccountType{get;init;}public bool?IsActive{get;init;}}public sealed class JournalQuery:PagedQuery{public JournalStatus?Status{get;init;}public long?FiscalPeriodId{get;init;}}
public sealed record LedgerAccountRow(long Id,string Code,string Name,string AccountType,bool AllowPosting,long CurrencyId,string CurrencyCode,bool IsActive);public sealed record JournalRow(long Id,string JournalNumber,DateOnly PostingDate,string SourceType,string SourceNumber,string Description,long CurrencyId,string CurrencyCode,decimal Debit,decimal Credit,string Status);public sealed record SaveLedgerAccountRequest(string Code,string Name,AccountType AccountType,long?ParentId,bool AllowPosting,long CurrencyId,bool IsActive);public sealed record CreateJournalLine(long LedgerAccountId,decimal Debit,decimal Credit,decimal ForeignDebit,decimal ForeignCredit,string?BusinessPartnerCode,string?ProductCode,string?WarehouseCode,string?Description);public sealed record CreateJournalRequest(string?JournalNumber,long FiscalPeriodId,DateOnly PostingDate,string SourceType,long SourceId,string SourceNumber,string?Description,long CurrencyId,decimal ExchangeRate,IReadOnlyList<CreateJournalLine>Lines);
public interface IAccountingService{Task<ApiResponse<PagedResult<LedgerAccountRow>>>GetAccountsAsync(LedgerAccountQuery q,CancellationToken ct);Task<ApiResponse<PagedResult<JournalRow>>>GetJournalsAsync(JournalQuery q,CancellationToken ct);Task<ApiResponse<SaveLedgerAccountRequest>>GetAccountAsync(long id,CancellationToken ct);Task<ApiResponse<object>>CreateAccountAsync(SaveLedgerAccountRequest r,CancellationToken ct);Task<ApiResponse<object>>UpdateAccountAsync(long id,SaveLedgerAccountRequest r,CancellationToken ct);Task<ApiResponse<object>>DeleteAccountAsync(long id,CancellationToken ct);Task<ApiResponse<object>>CreateJournalAsync(CreateJournalRequest r,CancellationToken ct);Task<ApiResponse<object>>PostJournalAsync(long id,CancellationToken ct);}

public sealed class AccountingService(IUnitOfWork u,IAccountingParameterService parameters,IHttpContextAccessor http):IAccountingService
{
 public async Task<ApiResponse<SaveLedgerAccountRequest>>GetAccountAsync(long id,CancellationToken ct){var e=await u.Repository<LedgerAccount>().GetByIdAsync(id,ct);return e is null?ApiResponse<SaveLedgerAccountRequest>.Error("Account not found.",404):ApiResponse<SaveLedgerAccountRequest>.Ok(new(e.Code,e.Name,e.AccountType,e.ParentId,e.AllowPosting,e.CurrencyId,e.IsActive));}
 public async Task<ApiResponse<object>>UpdateAccountAsync(long id,SaveLedgerAccountRequest r,CancellationToken ct){var e=await u.Repository<LedgerAccount>().GetByIdForUpdateAsync(id,ct);if(e is null)return ApiResponse<object>.Error("Account not found.",404);var code=r.Code.Trim().ToUpperInvariant();if(string.IsNullOrWhiteSpace(code)||string.IsNullOrWhiteSpace(r.Name))return ApiResponse<object>.Error("Account code and name are required.",400);if(await u.Repository<LedgerAccount>().ExistsAsync(x=>x.Id!=id&&x.Code==code,ct))return ApiResponse<object>.Error("Account code exists.",409);if(r.ParentId==id)return ApiResponse<object>.Error("An account cannot be its own parent.",400);if(r.ParentId.HasValue&&!await u.Repository<LedgerAccount>().ExistsAsync(x=>x.Id==r.ParentId&&x.IsActive,ct))return ApiResponse<object>.Error("Active parent account was not found.",400);var currency=await u.Repository<Currency>().FirstOrDefaultAsync(x=>x.Id==r.CurrencyId&&x.IsActive,false,ct);if(currency is null)return ApiResponse<object>.Error("An active defined currency is required.",400);e.Code=code;e.Name=r.Name.Trim();e.AccountType=r.AccountType;e.ParentId=r.ParentId;e.AllowPosting=r.AllowPosting;e.CurrencyId=currency.Id;e.CurrencyCode=currency.IsoCode;e.IsActive=r.IsActive;await u.SaveChangesAsync(ct);return ApiResponse<object>.Ok(new{e.Id});}
 public async Task<ApiResponse<object>>DeleteAccountAsync(long id,CancellationToken ct){var e=await u.Repository<LedgerAccount>().GetByIdForUpdateAsync(id,ct);if(e is null)return ApiResponse<object>.Error("Account not found.",404);if(await u.Repository<LedgerAccount>().ExistsAsync(x=>x.ParentId==id,ct)||await u.Repository<JournalEntryLine>().ExistsAsync(x=>x.LedgerAccountId==id,ct))return ApiResponse<object>.Error("Account is in use and cannot be deleted.",409);u.Repository<LedgerAccount>().Remove(e);await u.SaveChangesAsync(ct);return ApiResponse<object>.Ok(new{e.Id});}
 public async Task<ApiResponse<PagedResult<LedgerAccountRow>>>GetAccountsAsync(LedgerAccountQuery q,CancellationToken ct){var x=u.Repository<LedgerAccount>().Query();if(q.AccountType.HasValue)x=x.Where(v=>v.AccountType==q.AccountType);if(q.IsActive.HasValue)x=x.Where(v=>v.IsActive==q.IsActive);if(!string.IsNullOrWhiteSpace(q.Search)){var s=q.Search.Trim();x=x.Where(v=>v.Code.Contains(s)||v.Name.Contains(s));}x=x.ApplyPagedFilters(q);var total=await x.CountAsync(ct);var rows=await x.OrderBy(v=>v.Code).Skip((q.NormalizedPageNumber-1)*q.NormalizedPageSize).Take(q.NormalizedPageSize).Select(v=>new LedgerAccountRow(v.Id,v.Code,v.Name,v.AccountType.ToString(),v.AllowPosting,v.CurrencyId,v.CurrencyCode,v.IsActive)).ToListAsync(ct);return ApiResponse<PagedResult<LedgerAccountRow>>.Ok(new(rows,q.NormalizedPageNumber,q.NormalizedPageSize,total));}
 public async Task<ApiResponse<PagedResult<JournalRow>>>GetJournalsAsync(JournalQuery q,CancellationToken ct){var x=u.Repository<JournalEntry>().Query().Include(v=>v.Lines).AsQueryable();if(q.Status.HasValue)x=x.Where(v=>v.Status==q.Status);if(q.FiscalPeriodId.HasValue)x=x.Where(v=>v.FiscalPeriodId==q.FiscalPeriodId);if(!string.IsNullOrWhiteSpace(q.Search)){var s=q.Search.Trim();x=x.Where(v=>v.JournalNumber.Contains(s)||v.SourceNumber.Contains(s));}x=x.ApplyPagedFilters(q);var total=await x.CountAsync(ct);var rows=await x.OrderByDescending(v=>v.PostingDate).ThenByDescending(v=>v.Id).Skip((q.NormalizedPageNumber-1)*q.NormalizedPageSize).Take(q.NormalizedPageSize).Select(v=>new JournalRow(v.Id,v.JournalNumber,v.PostingDate,v.SourceType,v.SourceNumber,v.Description??"",v.CurrencyId,v.CurrencyCode,v.Lines.Sum(l=>l.Debit),v.Lines.Sum(l=>l.Credit),v.Status.ToString())).ToListAsync(ct);return ApiResponse<PagedResult<JournalRow>>.Ok(new(rows,q.NormalizedPageNumber,q.NormalizedPageSize,total));}
 public async Task<ApiResponse<object>>CreateAccountAsync(SaveLedgerAccountRequest r,CancellationToken ct){var code=r.Code.Trim().ToUpperInvariant();if(string.IsNullOrWhiteSpace(code)||string.IsNullOrWhiteSpace(r.Name))return ApiResponse<object>.Error("Account code and name are required.",400);if(await u.Repository<LedgerAccount>().ExistsAsync(x=>x.Code==code,ct))return ApiResponse<object>.Error("Account code exists.",409);if(r.ParentId.HasValue&&!await u.Repository<LedgerAccount>().ExistsAsync(x=>x.Id==r.ParentId&&x.IsActive,ct))return ApiResponse<object>.Error("Active parent account was not found.",400);var currency=await u.Repository<Currency>().FirstOrDefaultAsync(x=>x.Id==r.CurrencyId&&x.IsActive,false,ct);if(currency is null)return ApiResponse<object>.Error("An active defined currency is required.",400);var e=new LedgerAccount{Code=code,Name=r.Name.Trim(),AccountType=r.AccountType,ParentId=r.ParentId,AllowPosting=r.AllowPosting,CurrencyId=currency.Id,CurrencyCode=currency.IsoCode,IsActive=r.IsActive};await u.Repository<LedgerAccount>().AddAsync(e,ct);await u.SaveChangesAsync(ct);return ApiResponse<object>.Ok(new{e.Id,e.CurrencyId,e.CurrencyCode});}
 public async Task<ApiResponse<object>>CreateJournalAsync(CreateJournalRequest r,CancellationToken ct)
 {
  var settings=await parameters.ResolveCurrentSettingsAsync(ct);if(r.Lines.Count<2)return ApiResponse<object>.Error("At least two lines are required.",400);var debit=Round(r.Lines.Sum(x=>x.Debit),settings.MonetaryDecimalPlaces);var credit=Round(r.Lines.Sum(x=>x.Credit),settings.MonetaryDecimalPlaces);if(debit<=0||Math.Abs(debit-credit)>settings.JournalBalanceTolerance)return ApiResponse<object>.Error("Journal entry is outside the configured balance tolerance.",400);var today=DateOnly.FromDateTime(DateTime.UtcNow);if(!settings.AllowBackdatedJournal&&r.PostingDate<today)return ApiResponse<object>.Error("Backdated journals are disabled by accounting parameters.",400);if(!settings.AllowFutureDatedJournal&&r.PostingDate>today)return ApiResponse<object>.Error("Future-dated journals are disabled by accounting parameters.",400);var period=await u.Repository<FiscalPeriod>().GetByIdAsync(r.FiscalPeriodId,ct);if(period is null||r.PostingDate<period.StartDate||r.PostingDate>period.EndDate||(settings.RequireOpenFiscalPeriod&&!period.IsOpen))return ApiResponse<object>.Error("Fiscal period is not available for the posting date.",409);if(settings.RequireJournalDescription&&string.IsNullOrWhiteSpace(r.Description))return ApiResponse<object>.Error("Journal description is required by accounting parameters.",400);if(settings.PreventDuplicateSourceDocument&&r.SourceId>0&&await u.Repository<JournalEntry>().ExistsAsync(x=>x.SourceType==r.SourceType&&x.SourceId==r.SourceId,ct))return ApiResponse<object>.Error("A journal already exists for this source document.",409);
  var accountIds=r.Lines.Select(x=>x.LedgerAccountId).Distinct().ToArray();var validAccounts=await u.Repository<LedgerAccount>().Query().Where(x=>accountIds.Contains(x.Id)&&x.IsActive&&(!settings.RequirePostingAccount||x.AllowPosting)).Select(x=>x.Id).CountAsync(ct);if(validAccounts!=accountIds.Length)return ApiResponse<object>.Error("Every journal line must use an active posting account.",400);
  var branchId=long.TryParse(http.HttpContext?.User.FindFirstValue("branchId"),out var b)?b:(long?)null;string number;try{number=await parameters.ResolveJournalNumberAsync(r.JournalNumber,branchId,ct);}catch(InvalidOperationException ex){return ApiResponse<object>.Error(ex.Message,400);}var currency=await u.Repository<Currency>().FirstOrDefaultAsync(x=>x.Id==r.CurrencyId&&x.IsActive,false,ct);if(currency is null)return ApiResponse<object>.Error("An active defined currency is required.",400);var rate=r.ExchangeRate>0?r.ExchangeRate:settings.DefaultExchangeRate;var e=new JournalEntry{JournalNumber=number,Status=settings.AutoPostManualJournals?JournalStatus.Posted:JournalStatus.Draft,FiscalPeriodId=r.FiscalPeriodId,PostingDate=r.PostingDate,SourceType=r.SourceType.Trim(),SourceId=r.SourceId,SourceNumber=r.SourceNumber.Trim(),Description=r.Description?.Trim(),CurrencyId=currency.Id,CurrencyCode=currency.IsoCode,ExchangeRate=rate,PostedAt=settings.AutoPostManualJournals?DateTime.UtcNow:null};var n=0;foreach(var l in r.Lines){if(l.Debit<0||l.Credit<0||(l.Debit>0&&l.Credit>0))return ApiResponse<object>.Error("Invalid journal line.",400);e.Lines.Add(new JournalEntryLine{LineNumber=++n,LedgerAccountId=l.LedgerAccountId,Debit=Round(l.Debit,settings.MonetaryDecimalPlaces),Credit=Round(l.Credit,settings.MonetaryDecimalPlaces),ForeignDebit=Round(l.ForeignDebit,settings.MonetaryDecimalPlaces),ForeignCredit=Round(l.ForeignCredit,settings.MonetaryDecimalPlaces),BusinessPartnerCode=l.BusinessPartnerCode?.Trim(),ProductCode=l.ProductCode?.Trim(),WarehouseCode=l.WarehouseCode?.Trim(),Description=l.Description?.Trim()});}await u.Repository<JournalEntry>().AddAsync(e,ct);await u.SaveChangesAsync(ct);return ApiResponse<object>.Ok(new{e.Id,e.JournalNumber,e.Status,e.CurrencyId,e.CurrencyCode});
 }
 public async Task<ApiResponse<object>>PostJournalAsync(long id,CancellationToken ct){var settings=await parameters.ResolveCurrentSettingsAsync(ct);var e=await u.Repository<JournalEntry>().Query(true).Include(x=>x.Lines).Include(x=>x.FiscalPeriod).FirstOrDefaultAsync(x=>x.Id==id,ct);if(e is null)return ApiResponse<object>.Error("Journal not found.",404);if(e.Status!=JournalStatus.Draft)return ApiResponse<object>.Error("Only draft journals can be posted.",409);if(Math.Abs(Round(e.Lines.Sum(x=>x.Debit),settings.MonetaryDecimalPlaces)-Round(e.Lines.Sum(x=>x.Credit),settings.MonetaryDecimalPlaces))>settings.JournalBalanceTolerance)return ApiResponse<object>.Error("Journal is outside the configured balance tolerance.",409);if(settings.RequireOpenFiscalPeriod&&!e.FiscalPeriod.IsOpen)return ApiResponse<object>.Error("Fiscal period is closed.",409);e.Status=JournalStatus.Posted;e.PostedAt=DateTime.UtcNow;await u.SaveChangesAsync(ct);return ApiResponse<object>.Ok(new{e.Id});}
 static decimal Round(decimal value,int places)=>Math.Round(value,places,MidpointRounding.AwayFromZero);
}


