using verii_metivon_api.Core.Domain;using verii_metivon_api.Modules.Inventory.Domain.Enums;using verii_metivon_api.Modules.Products.Domain.Enums;using verii_metivon_api.Modules.Warehouses.Domain.Entities;
namespace verii_metivon_api.Modules.Accounting.Domain.Entities;public enum AccountType{Asset=1,Liability=2,Equity=3,Revenue=4,Expense=5,OffBalance=6}public enum JournalStatus{Draft=0,Posted=1,Reversed=2,Cancelled=3}public enum CostCloseStatus{Draft=0,Running=1,Completed=2,Failed=3,Reopened=4}
public sealed class LedgerAccount:Entity{public string Code{get;set;}=string.Empty;public string Name{get;set;}=string.Empty;public AccountType AccountType{get;set;}public long?ParentId{get;set;}public LedgerAccount?Parent{get;set;}public bool AllowPosting{get;set;}=true;public long CurrencyId{get;set;}public Currency Currency{get;set;}=null!;public string CurrencyCode{get;set;}="TRY";public bool IsActive{get;set;}=true;}
public sealed class FiscalPeriod:Entity{public string Code{get;set;}=string.Empty;public string Name{get;set;}=string.Empty;public DateOnly StartDate{get;set;}public DateOnly EndDate{get;set;}public bool IsOpen{get;set;}=true;public bool IsInventoryClosed{get;set;}public bool IsGeneralLedgerClosed{get;set;}}
public sealed class InventoryPostingProfile:Entity{public string Code{get;set;}=string.Empty;public string Name{get;set;}=string.Empty;public InventoryMovementType MovementType{get;set;}public long DebitAccountId{get;set;}public LedgerAccount DebitAccount{get;set;}=null!;public long CreditAccountId{get;set;}public LedgerAccount CreditAccount{get;set;}=null!;public long?ProductGroupId{get;set;}public long?WarehouseId{get;set;}public int Priority{get;set;}public bool IsActive{get;set;}=true;}
public sealed class JournalEntry:Entity{public string JournalNumber{get;set;}=string.Empty;public JournalStatus Status{get;set;}public long FiscalPeriodId{get;set;}public FiscalPeriod FiscalPeriod{get;set;}=null!;public DateOnly PostingDate{get;set;}public string SourceType{get;set;}=string.Empty;public long SourceId{get;set;}public string SourceNumber{get;set;}=string.Empty;public string?Description{get;set;}public long CurrencyId{get;set;}public Currency Currency{get;set;}=null!;public string CurrencyCode{get;set;}="TRY";public decimal ExchangeRate{get;set;}=1;public DateTime?PostedAt{get;set;}public long?ReversalOfId{get;set;}public JournalEntry?ReversalOf{get;set;}public ICollection<JournalEntryLine>Lines{get;set;}=new List<JournalEntryLine>();}
public sealed class JournalEntryLine:Entity{public long JournalEntryId{get;set;}public JournalEntry JournalEntry{get;set;}=null!;public int LineNumber{get;set;}public long LedgerAccountId{get;set;}public LedgerAccount LedgerAccount{get;set;}=null!;public decimal Debit{get;set;}public decimal Credit{get;set;}public decimal ForeignDebit{get;set;}public decimal ForeignCredit{get;set;}public string?BusinessPartnerCode{get;set;}public string?ProductCode{get;set;}public string?WarehouseCode{get;set;}public string?Description{get;set;}}
public sealed class InventoryCostClose:Entity{public string CloseNumber{get;set;}=string.Empty;public long FiscalPeriodId{get;set;}public FiscalPeriod FiscalPeriod{get;set;}=null!;public CostCloseStatus Status{get;set;}public DateTime?StartedAt{get;set;}public DateTime?CompletedAt{get;set;}public int TransactionCount{get;set;}public decimal AdjustmentAmount{get;set;}public string?ErrorMessage{get;set;}}
public sealed class AccountingParameterSettings:Entity
{
 public long?BranchId{get;set;}public Branch?Branch{get;set;}public long?WarehouseId{get;set;}public Warehouse?Warehouse{get;set;}
 public long DefaultCurrencyId{get;set;}public Currency DefaultCurrency{get;set;}=null!;public string DefaultCurrencyCode{get;set;}="TRY";public decimal DefaultExchangeRate{get;set;}=1;public int MonetaryDecimalPlaces{get;set;}=2;public decimal JournalBalanceTolerance{get;set;}=0.01m;
 public bool RequireOpenFiscalPeriod{get;set;}=true;public bool AllowBackdatedJournal{get;set;}=true;public bool AllowFutureDatedJournal{get;set;}public bool AutoPostManualJournals{get;set;}public bool RequirePostingAccount{get;set;}=true;public bool RequireJournalDescription{get;set;}public bool PreventDuplicateSourceDocument{get;set;}=true;
 public InventoryValuationMethod DefaultInventoryValuationMethod{get;set;}=InventoryValuationMethod.Fifo;public bool RequireInventoryPostingProfile{get;set;}public bool CreateCostLayersOnReceipt{get;set;}=true;public bool AllowNegativeInventoryValue{get;set;}public int CostDecimalPlaces{get;set;}=6;
 public decimal CostCloseTolerance{get;set;}=0.01m;public bool RequireApprovalBeforeCostClose{get;set;}=true;public bool AllowCostCloseReopen{get;set;}public bool AutoCloseInventoryWithPeriod{get;set;}public bool IncludeLandedCostAdjustments{get;set;}=true;
 public byte[]RowVersion{get;set;}=[];
}
