using verii_metivon_api.Core.Domain;
using verii_metivon_api.Modules.Accounting.Domain.Entities;
using verii_metivon_api.Modules.Inventory.Domain.Entities;
using verii_metivon_api.Modules.Procurement.Domain.Entities;
using verii_metivon_api.Modules.Products.Domain.Entities;
using verii_metivon_api.Modules.Receiving.Domain.Entities;
namespace verii_metivon_api.Modules.LandedCosts.Domain.Entities;
public enum ImportDossierStatus{Draft=0,InTransit=1,ReceivedProvisionally=2,ReadyForAllocation=3,Allocated=4,Finalized=5,Closed=6,Cancelled=7}
public enum LandedCostAllocationMethod{Amount=1,Quantity=2,Weight=3,Volume=4,Equal=5,Manual=6}
public enum LandedCostAmountType{Estimated=1,Actual=2,Adjustment=3,Credit=4}
public enum LandedCostSourceType{PurchaseInvoice=1,PaymentReceipt=2,BankReceipt=3,CustomsAssessment=4,Other=5}
public enum ImportDocumentType{CustomsDeclaration=1,CommercialInvoice=2,FreightDocument=3,InsurancePolicy=4,CertificateOfOrigin=5,PaymentReceipt=6,BankReceipt=7,PurchaseInvoice=8,InspectionCertificate=9,Other=10}
public sealed class LandedCostType:DefinitionEntity{public LandedCostAllocationMethod DefaultAllocationMethod{get;set;}=LandedCostAllocationMethod.Amount;public bool IncludeInCustomsValue{get;set;}public bool CapitalizeToInventory{get;set;}=true;public long?ClearingAccountId{get;set;}public LedgerAccount?ClearingAccount{get;set;}public long?VarianceAccountId{get;set;}public LedgerAccount?VarianceAccount{get;set;}}
public sealed class ImportDossier:Entity{public long?TradeDossierId{get;set;}public string DossierNumber{get;set;}=string.Empty;public ImportDossierStatus Status{get;set;}public long BranchId{get;set;}public long SupplierId{get;set;}public BusinessPartner Supplier{get;set;}=null!;public string CurrencyCode{get;set;}="USD";public string IncotermCode{get;set;}="FOB";public string?CustomsDeclarationNumber{get;set;}public DateOnly?CustomsDeclarationDate{get;set;}public decimal TransactionExchangeRate{get;set;}=1;public decimal CustomsExchangeRate{get;set;}=1;public decimal CostingExchangeRate{get;set;}=1;public DateOnly OpenDate{get;set;}public DateOnly?EstimatedArrivalDate{get;set;}public DateOnly?ActualArrivalDate{get;set;}public DateTime?FinalizedAt{get;set;}public int AllocationRevision{get;set;}public string?Notes{get;set;}public ICollection<ImportDossierLine>Lines{get;set;}=new List<ImportDossierLine>();public ICollection<ImportDossierCost>Costs{get;set;}=new List<ImportDossierCost>();}
public sealed class ImportDossierLine:Entity{public long ImportDossierId{get;set;}public ImportDossier ImportDossier{get;set;}=null!;public int LineNumber{get;set;}public long?PurchaseOrderLineId{get;set;}public PurchaseOrderLine?PurchaseOrderLine{get;set;}public long?GoodsReceiptLineId{get;set;}public GoodsReceiptLine?GoodsReceiptLine{get;set;}public long ProductId{get;set;}public Product Product{get;set;}=null!;public decimal Quantity{get;set;}public decimal NetWeight{get;set;}public decimal GrossWeight{get;set;}public decimal Volume{get;set;}public decimal ForeignUnitPrice{get;set;}public decimal ForeignGoodsAmount{get;set;}public decimal TransactionExchangeRate{get;set;}public decimal CustomsExchangeRate{get;set;}public decimal CostingExchangeRate{get;set;}public decimal GoodsAmountLocal{get;set;}public decimal AllocatedCostLocal{get;set;}public decimal FinalUnitCostLocal{get;set;}public long?ReceiptTransactionId{get;set;}public InventoryTransaction?ReceiptTransaction{get;set;}public ICollection<ImportDossierAllocation>Allocations{get;set;}=new List<ImportDossierAllocation>();}
public sealed class ImportDossierCost:Entity{public long ImportDossierId{get;set;}public ImportDossier ImportDossier{get;set;}=null!;public long LandedCostTypeId{get;set;}public LandedCostType LandedCostType{get;set;}=null!;public LandedCostAmountType AmountType{get;set;}public LandedCostAllocationMethod AllocationMethod{get;set;}public LandedCostSourceType SourceType{get;set;}=LandedCostSourceType.PurchaseInvoice;public long?SupplierId{get;set;}public string?InvoiceNumber{get;set;}public DateOnly?InvoiceDate{get;set;}public string?PaymentReference{get;set;}public DateOnly?PaymentDate{get;set;}public string CurrencyCode{get;set;}="TRY";public decimal ForeignAmount{get;set;}public decimal ExchangeRate{get;set;}=1;public decimal LocalAmount{get;set;}public string?Description{get;set;}public ICollection<ImportDossierAllocation>Allocations{get;set;}=new List<ImportDossierAllocation>();}
public sealed class ImportDossierAllocation:Entity{public long ImportDossierCostId{get;set;}public ImportDossierCost ImportDossierCost{get;set;}=null!;public long ImportDossierLineId{get;set;}public ImportDossierLine ImportDossierLine{get;set;}=null!;public int Revision{get;set;}public decimal BasisValue{get;set;}public decimal AllocationRate{get;set;}public decimal AllocatedAmount{get;set;}public bool IsManual{get;set;}}
public sealed class ImportDossierDocument:Entity{public long ImportDossierId{get;set;}public ImportDossier ImportDossier{get;set;}=null!;public long?ImportDossierCostId{get;set;}public ImportDossierCost?ImportDossierCost{get;set;}public ImportDocumentType DocumentType{get;set;}public string DocumentNumber{get;set;}=string.Empty;public DateOnly?DocumentDate{get;set;}public string OriginalFileName{get;set;}=string.Empty;public string StoredFileName{get;set;}=string.Empty;public string ContentType{get;set;}=string.Empty;public long FileSize{get;set;}public string Sha256{get;set;}=string.Empty;public string?Notes{get;set;}}
