using Microsoft.EntityFrameworkCore;
using verii_metivon_api.Core.Auth;
using verii_metivon_api.Core.Domain;
using verii_metivon_api.Core.Paging;
using verii_metivon_api.Core.UnitOfWork;
using verii_metivon_api.Modules.Warehouses.Domain.Entities;
using verii_metivon_api.Modules.Warehouses.Application.Parameters;
namespace verii_metivon_api.Modules.Warehouses.Application.Services;
public sealed class WarehouseService(IUnitOfWork u, IWarehouseParameterService parameters) : IWarehouseService
{
    public async Task<ApiResponse<PagedResult<WarehouseRow>>> GetWarehousesAsync(WarehouseListQuery q, CancellationToken ct) { var x = u.Repository<Warehouse>().Query().Include(v => v.Branch).Include(v => v.WarehouseType).AsQueryable(); if (q.BranchId.HasValue) x = x.Where(v => v.BranchId == q.BranchId); if (q.IsActive.HasValue) x = x.Where(v => v.IsActive == q.IsActive); if (!string.IsNullOrWhiteSpace(q.Search)) { var s = q.Search.Trim(); x = x.Where(v => v.Code.Contains(s) || v.Name.Contains(s)); } x = x.ApplyPagedFilters(q); var total = await x.CountAsync(ct); x = (q.SortBy?.ToLowerInvariant()) switch { "name" => q.SortDirection == "desc" ? x.OrderByDescending(v => v.Name) : x.OrderBy(v => v.Name), _ => q.SortDirection == "desc" ? x.OrderByDescending(v => v.Code) : x.OrderBy(v => v.Code) }; var items = await x.Skip((q.NormalizedPageNumber - 1) * q.NormalizedPageSize).Take(q.NormalizedPageSize).Select(v => new WarehouseRow(v.Id, v.Code, v.Name, v.BranchId, v.Branch.Name, v.WarehouseType.Name, v.IsWmsEnabled, v.AllowNegativeStock, v.IsDefault, v.IsActive)).ToListAsync(ct); return ApiResponse<PagedResult<WarehouseRow>>.Ok(new(items, q.NormalizedPageNumber, q.NormalizedPageSize, total)); }
    public async Task<ApiResponse<PagedResult<LocationRow>>> GetLocationsAsync(LocationListQuery q, CancellationToken ct) { var x = u.Repository<StorageLocation>().Query().Include(v => v.Warehouse).Include(v => v.WarehouseZone).Include(v => v.LocationType).AsQueryable(); if (q.WarehouseId.HasValue) x = x.Where(v => v.WarehouseId == q.WarehouseId); if (q.ZoneId.HasValue) x = x.Where(v => v.WarehouseZoneId == q.ZoneId); if (q.IsActive.HasValue) x = x.Where(v => v.IsActive == q.IsActive); if (!string.IsNullOrWhiteSpace(q.Search)) { var s = q.Search.Trim(); x = x.Where(v => v.Code.Contains(s) || (v.Barcode != null && v.Barcode.Contains(s))); } x = x.ApplyPagedFilters(q); var total = await x.CountAsync(ct); x = x.OrderBy(v => v.Warehouse.Code).ThenBy(v => v.Code); var items = await x.Skip((q.NormalizedPageNumber - 1) * q.NormalizedPageSize).Take(q.NormalizedPageSize).Select(v => new LocationRow(v.Id, v.Code, v.Barcode, v.WarehouseId, v.Warehouse.Name, v.WarehouseZone != null ? v.WarehouseZone.Name : null, v.LocationType.Name, (v.Aisle ?? "") + "-" + (v.Bay ?? "") + "-" + (v.Level ?? "") + "-" + (v.Position ?? ""), v.IsBlocked, v.IsActive)).ToListAsync(ct); return ApiResponse<PagedResult<LocationRow>>.Ok(new(items, q.NormalizedPageNumber, q.NormalizedPageSize, total)); }
    public async Task<ApiResponse<object>> GetWarehouseAsync(long id, CancellationToken ct) { var e = await u.Repository<Warehouse>().Query().AsNoTracking().Where(x => x.Id == id).Select(x => new { x.Id, x.Code, x.Name, x.BranchId, x.WarehouseTypeId, x.Address, x.City, x.CountryCode, x.AllowNegativeStock, x.IsWmsEnabled, x.IsDefault, x.IsActive }).FirstOrDefaultAsync(ct); return e is null ? ApiResponse<object>.Error("Warehouse not found.", 404) : ApiResponse<object>.Ok(e); }
    public async Task<ApiResponse<object>> GetLocationAsync(long id, CancellationToken ct) { var e = await u.Repository<StorageLocation>().Query().AsNoTracking().Where(x => x.Id == id).Select(x => new { x.Id, x.WarehouseId, x.WarehouseZoneId, x.LocationTypeId, x.Code, x.Barcode, x.Aisle, x.Bay, x.Level, x.Position, x.MaximumWeight, x.MaximumVolume, x.MaximumQuantity, x.IsReceiving, x.IsShipping, x.IsQuarantine, x.IsBlocked, x.IsActive }).FirstOrDefaultAsync(ct); return e is null ? ApiResponse<object>.Error("Storage location not found.", 404) : ApiResponse<object>.Ok(e); }
    public async Task<ApiResponse<object>> CreateWarehouseAsync(SaveWarehouseRequest r, CancellationToken ct) { var code = r.Code.Trim().ToUpperInvariant(); if (await u.Repository<Warehouse>().ExistsAsync(x => x.Code == code, ct)) return ApiResponse<object>.Error("Warehouse code already exists.", 409); var settings = await parameters.GetAsync(r.BranchId, null, ct); var e = new Warehouse { Code = code, Name = r.Name.Trim(), BranchId = r.BranchId, WarehouseTypeId = r.WarehouseTypeId, Address = r.Address, City = r.City, CountryCode = r.CountryCode, AllowNegativeStock = r.AllowNegativeStock ?? settings.AllowNegativeStockByDefault, IsWmsEnabled = r.IsWmsEnabled, IsDefault = r.IsDefault, IsActive = r.IsActive }; await u.ExecuteInTransactionAsync(async t => { if (e.IsDefault) { var defs = await u.Repository<Warehouse>().Query(true).Where(x => x.BranchId == e.BranchId && x.IsDefault).ToListAsync(t); defs.ForEach(x => x.IsDefault = false); } await u.Repository<Warehouse>().AddAsync(e, t); await u.SaveChangesAsync(t); }, ct); return ApiResponse<object>.Ok(new { e.Id }); }
    public async Task<ApiResponse<object>> CreateLocationAsync(SaveLocationRequest r, CancellationToken ct) { var validation=await ValidateLocationAsync(r,ct);if(validation is not null)return validation;var code = r.Code.Trim().ToUpperInvariant(); if (await u.Repository<StorageLocation>().ExistsAsync(x => x.WarehouseId == r.WarehouseId && x.Code == code, ct)) return ApiResponse<object>.Error("Location code already exists.", 409); var e = new StorageLocation { WarehouseId = r.WarehouseId, WarehouseZoneId = r.WarehouseZoneId, LocationTypeId = r.LocationTypeId, Code = code, Barcode = r.Barcode?.Trim(), Aisle = r.Aisle?.Trim(), Bay = r.Bay?.Trim(), Level = r.Level?.Trim(), Position = r.Position?.Trim(), MaximumWeight = r.MaximumWeight, MaximumVolume = r.MaximumVolume, MaximumQuantity = r.MaximumQuantity, IsReceiving = r.IsReceiving, IsShipping = r.IsShipping, IsQuarantine = r.IsQuarantine, IsBlocked = r.IsBlocked, IsActive = r.IsActive }; await u.Repository<StorageLocation>().AddAsync(e, ct); try{await u.SaveChangesAsync(ct);}catch(DbUpdateException){return ApiResponse<object>.Error("Storage location could not be saved. Verify warehouse, zone and location type selections.",400);}return ApiResponse<object>.Ok(new { e.Id }); }
    public async Task<ApiResponse<object>> UpdateWarehouseAsync(long id, SaveWarehouseRequest r, CancellationToken ct) { var e = await u.Repository<Warehouse>().GetByIdForUpdateAsync(id, ct); if (e is null) return ApiResponse<object>.Error("Warehouse not found.", 404); var code = r.Code.Trim().ToUpperInvariant(); if (await u.Repository<Warehouse>().ExistsAsync(x => x.Id != id && x.Code == code, ct)) return ApiResponse<object>.Error("Warehouse code already exists.", 409); await u.ExecuteInTransactionAsync(async t => { if (r.IsDefault) { var defs = await u.Repository<Warehouse>().Query(true).Where(x => x.Id != id && x.BranchId == r.BranchId && x.IsDefault).ToListAsync(t); defs.ForEach(x => x.IsDefault = false); } e.Code = code; e.Name = r.Name.Trim(); e.BranchId = r.BranchId; e.WarehouseTypeId = r.WarehouseTypeId; e.Address = r.Address; e.City = r.City; e.CountryCode = r.CountryCode; e.AllowNegativeStock = r.AllowNegativeStock ?? e.AllowNegativeStock; e.IsWmsEnabled = r.IsWmsEnabled; e.IsDefault = r.IsDefault; e.IsActive = r.IsActive; await u.SaveChangesAsync(t); }, ct); return ApiResponse<object>.Ok(new { e.Id }); }
    public async Task<ApiResponse<object>> UpdateLocationAsync(long id, SaveLocationRequest r, CancellationToken ct) { var validation=await ValidateLocationAsync(r,ct);if(validation is not null)return validation;var e = await u.Repository<StorageLocation>().GetByIdForUpdateAsync(id, ct); if (e is null) return ApiResponse<object>.Error("Storage location not found.", 404); var code = r.Code.Trim().ToUpperInvariant(); if (await u.Repository<StorageLocation>().ExistsAsync(x => x.Id != id && x.WarehouseId == r.WarehouseId && x.Code == code, ct)) return ApiResponse<object>.Error("Location code already exists.", 409); e.WarehouseId = r.WarehouseId; e.WarehouseZoneId = r.WarehouseZoneId; e.LocationTypeId = r.LocationTypeId; e.Code = code; e.Barcode = r.Barcode?.Trim(); e.Aisle = r.Aisle?.Trim(); e.Bay = r.Bay?.Trim(); e.Level = r.Level?.Trim(); e.Position = r.Position?.Trim(); e.MaximumWeight = r.MaximumWeight; e.MaximumVolume = r.MaximumVolume; e.MaximumQuantity = r.MaximumQuantity; e.IsReceiving = r.IsReceiving; e.IsShipping = r.IsShipping; e.IsQuarantine = r.IsQuarantine; e.IsBlocked = r.IsBlocked; e.IsActive = r.IsActive; await u.SaveChangesAsync(ct); return ApiResponse<object>.Ok(new { e.Id }); }
    public async Task<ApiResponse<object>> DeleteWarehouseAsync(long id, CancellationToken ct) { var e = await u.Repository<Warehouse>().GetByIdForUpdateAsync(id, ct); if (e is null) return ApiResponse<object>.Error("Warehouse not found.", 404); if (e.IsDefault) return ApiResponse<object>.Error("Default warehouse cannot be deleted.", 409); if (await u.Repository<StorageLocation>().ExistsAsync(x => x.WarehouseId == id, ct)) return ApiResponse<object>.Error("Warehouse with storage locations cannot be deleted; deactivate it instead.", 409); e.IsDeleted = true; e.DeletedAt = DateTime.UtcNow; e.IsActive = false; await u.SaveChangesAsync(ct); return ApiResponse<object>.Ok(new { e.Id }); }
    public async Task<ApiResponse<object>> DeleteLocationAsync(long id, CancellationToken ct) { var e = await u.Repository<StorageLocation>().GetByIdForUpdateAsync(id, ct); if (e is null) return ApiResponse<object>.Error("Storage location not found.", 404); e.IsDeleted = true; e.DeletedAt = DateTime.UtcNow; e.IsActive = false; await u.SaveChangesAsync(ct); return ApiResponse<object>.Ok(new { e.Id }); }
    private async Task<ApiResponse<object>?> ValidateLocationAsync(SaveLocationRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Code))return ApiResponse<object>.Error("Location code is required.",400);if(!await u.Repository<Warehouse>().ExistsAsync(x=>x.Id==r.WarehouseId&&x.IsActive,ct))return ApiResponse<object>.Error("An active warehouse is required.",400);if(!await u.Repository<LocationType>().ExistsAsync(x=>x.Id==r.LocationTypeId&&x.IsActive,ct))return ApiResponse<object>.Error("An active location type is required.",400);if(r.WarehouseZoneId.HasValue&&!await u.Repository<WarehouseZone>().ExistsAsync(x=>x.Id==r.WarehouseZoneId&&x.WarehouseId==r.WarehouseId&&x.IsActive,ct))return ApiResponse<object>.Error("The selected zone must be active and belong to the warehouse.",400);return null;}
}


