using Microsoft.EntityFrameworkCore;using verii_metivon_api.Core.Auth;using verii_metivon_api.Core.Domain;using verii_metivon_api.Core.Paging;using verii_metivon_api.Core.UnitOfWork;using verii_metivon_api.Modules.Warehouses.Domain.Entities;using verii_metivon_api.Modules.Warehouses.Application.Parameters;
namespace verii_metivon_api.Modules.Warehouses.Application.Services;
public sealed class WarehouseService(IUnitOfWork u,IWarehouseParameterService parameters):IWarehouseService{
 public async Task<ApiResponse<PagedResult<WarehouseRow>>>GetWarehousesAsync(WarehouseListQuery q,CancellationToken ct){var x=u.Repository<Warehouse>().Query().Include(v=>v.Branch).Include(v=>v.WarehouseType).AsQueryable();if(q.BranchId.HasValue)x=x.Where(v=>v.BranchId==q.BranchId);if(q.IsActive.HasValue)x=x.Where(v=>v.IsActive==q.IsActive);if(!string.IsNullOrWhiteSpace(q.Search)){var s=q.Search.Trim();x=x.Where(v=>v.Code.Contains(s)||v.Name.Contains(s));}x=x.ApplyPagedFilters(q);var total=await x.CountAsync(ct);x=(q.SortBy?.ToLowerInvariant())switch{"name"=>q.SortDirection=="desc"?x.OrderByDescending(v=>v.Name):x.OrderBy(v=>v.Name),_=>q.SortDirection=="desc"?x.OrderByDescending(v=>v.Code):x.OrderBy(v=>v.Code)};var items=await x.Skip((q.NormalizedPageNumber-1)*q.NormalizedPageSize).Take(q.NormalizedPageSize).Select(v=>new WarehouseRow(v.Id,v.Code,v.Name,v.BranchId,v.Branch.Name,v.WarehouseType.Name,v.IsWmsEnabled,v.AllowNegativeStock,v.IsDefault,v.IsActive)).ToListAsync(ct);return ApiResponse<PagedResult<WarehouseRow>>.Ok(new(items,q.NormalizedPageNumber,q.NormalizedPageSize,total));}
 public async Task<ApiResponse<PagedResult<LocationRow>>>GetLocationsAsync(LocationListQuery q,CancellationToken ct){var x=u.Repository<StorageLocation>().Query().Include(v=>v.Warehouse).Include(v=>v.WarehouseZone).Include(v=>v.LocationType).AsQueryable();if(q.WarehouseId.HasValue)x=x.Where(v=>v.WarehouseId==q.WarehouseId);if(q.ZoneId.HasValue)x=x.Where(v=>v.WarehouseZoneId==q.ZoneId);if(q.IsActive.HasValue)x=x.Where(v=>v.IsActive==q.IsActive);if(!string.IsNullOrWhiteSpace(q.Search)){var s=q.Search.Trim();x=x.Where(v=>v.Code.Contains(s)||(v.Barcode!=null&&v.Barcode.Contains(s)));}x=x.ApplyPagedFilters(q);var total=await x.CountAsync(ct);x=x.OrderBy(v=>v.Warehouse.Code).ThenBy(v=>v.Code);var items=await x.Skip((q.NormalizedPageNumber-1)*q.NormalizedPageSize).Take(q.NormalizedPageSize).Select(v=>new LocationRow(v.Id,v.Code,v.Barcode,v.WarehouseId,v.Warehouse.Name,v.WarehouseZone!=null?v.WarehouseZone.Name:null,v.LocationType.Name,(v.Aisle??"")+"-"+(v.Bay??"")+"-"+(v.Level??"")+"-"+(v.Position??""),v.IsBlocked,v.IsActive)).ToListAsync(ct);return ApiResponse<PagedResult<LocationRow>>.Ok(new(items,q.NormalizedPageNumber,q.NormalizedPageSize,total));}
 public async Task<ApiResponse<object>>CreateWarehouseAsync(SaveWarehouseRequest r,CancellationToken ct){var code=r.Code.Trim().ToUpperInvariant();if(await u.Repository<Warehouse>().ExistsAsync(x=>x.Code==code,ct))return ApiResponse<object>.Error("Warehouse code already exists.",409);var settings=await parameters.GetAsync(r.BranchId,null,ct);var e=new Warehouse{Code=code,Name=r.Name.Trim(),BranchId=r.BranchId,WarehouseTypeId=r.WarehouseTypeId,Address=r.Address,City=r.City,CountryCode=r.CountryCode,AllowNegativeStock=r.AllowNegativeStock??settings.AllowNegativeStockByDefault,IsWmsEnabled=r.IsWmsEnabled,IsDefault=r.IsDefault,IsActive=r.IsActive};await u.ExecuteInTransactionAsync(async t=>{if(e.IsDefault){var defs=await u.Repository<Warehouse>().Query(true).Where(x=>x.BranchId==e.BranchId&&x.IsDefault).ToListAsync(t);defs.ForEach(x=>x.IsDefault=false);}await u.Repository<Warehouse>().AddAsync(e,t);await u.SaveChangesAsync(t);},ct);return ApiResponse<object>.Ok(new{e.Id});}
 public async Task<ApiResponse<object>>CreateLocationAsync(SaveLocationRequest r,CancellationToken ct){var code=r.Code.Trim().ToUpperInvariant();if(await u.Repository<StorageLocation>().ExistsAsync(x=>x.WarehouseId==r.WarehouseId&&x.Code==code,ct))return ApiResponse<object>.Error("Location code already exists.",409);var e=new StorageLocation{WarehouseId=r.WarehouseId,WarehouseZoneId=r.WarehouseZoneId,LocationTypeId=r.LocationTypeId,Code=code,Barcode=r.Barcode,Aisle=r.Aisle,Bay=r.Bay,Level=r.Level,Position=r.Position,MaximumWeight=r.MaximumWeight,MaximumVolume=r.MaximumVolume,MaximumQuantity=r.MaximumQuantity,IsReceiving=r.IsReceiving,IsShipping=r.IsShipping,IsQuarantine=r.IsQuarantine,IsBlocked=r.IsBlocked,IsActive=r.IsActive};await u.Repository<StorageLocation>().AddAsync(e,ct);await u.SaveChangesAsync(ct);return ApiResponse<object>.Ok(new{e.Id});}}


