using System.Data;
using System.Security.Claims;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using verii_metivon_api.Core.Persistence;
using verii_metivon_api.Modules.Accounting.Domain.Entities;
using verii_metivon_api.Modules.Parameters.Domain.Entities;
using verii_metivon_api.Modules.Products.Domain.Enums;

namespace verii_metivon_api.Modules.Accounting.Application.Parameters;

public sealed record AccountingParametersDto(long?BranchId,long?WarehouseId,bool JournalIsAutomatic,bool JournalAllowManual,string JournalFormat,long JournalNextNumber,int JournalIncrementBy,long JournalMinimumNumber,long JournalMaximumNumber,string DefaultCurrencyCode,decimal DefaultExchangeRate,int MonetaryDecimalPlaces,decimal JournalBalanceTolerance,bool RequireOpenFiscalPeriod,bool AllowBackdatedJournal,bool AllowFutureDatedJournal,bool AutoPostManualJournals,bool RequirePostingAccount,bool RequireJournalDescription,bool PreventDuplicateSourceDocument,int DefaultInventoryValuationMethod,bool RequireInventoryPostingProfile,bool CreateCostLayersOnReceipt,bool AllowNegativeInventoryValue,int CostDecimalPlaces,decimal CostCloseTolerance,bool RequireApprovalBeforeCostClose,bool AllowCostCloseReopen,bool AutoCloseInventoryWithPeriod,bool IncludeLandedCostAdjustments,string JournalPreview);
public sealed record SaveAccountingParametersRequest(long?BranchId,long?WarehouseId,bool JournalIsAutomatic,bool JournalAllowManual,string JournalFormat,long JournalNextNumber,int JournalIncrementBy,long JournalMinimumNumber,long JournalMaximumNumber,string DefaultCurrencyCode,decimal DefaultExchangeRate,int MonetaryDecimalPlaces,decimal JournalBalanceTolerance,bool RequireOpenFiscalPeriod,bool AllowBackdatedJournal,bool AllowFutureDatedJournal,bool AutoPostManualJournals,bool RequirePostingAccount,bool RequireJournalDescription,bool PreventDuplicateSourceDocument,int DefaultInventoryValuationMethod,bool RequireInventoryPostingProfile,bool CreateCostLayersOnReceipt,bool AllowNegativeInventoryValue,int CostDecimalPlaces,decimal CostCloseTolerance,bool RequireApprovalBeforeCostClose,bool AllowCostCloseReopen,bool AutoCloseInventoryWithPeriod,bool IncludeLandedCostAdjustments);
public interface IAccountingParameterService
{
 Task<AccountingParametersDto>GetAsync(long?branchId,long?warehouseId,CancellationToken ct);Task<AccountingParametersDto>SaveAsync(SaveAccountingParametersRequest r,CancellationToken ct);Task<AccountingParameterSettings>ResolveSettingsAsync(long?branchId,long?warehouseId,CancellationToken ct);Task<AccountingParameterSettings>ResolveCurrentSettingsAsync(CancellationToken ct);Task<string>ResolveJournalNumberAsync(string?requested,long?branchId,CancellationToken ct);
}

public sealed class AccountingParameterService(MetivonDbContext db,IHttpContextAccessor http):IAccountingParameterService
{
 const string Module="Accounting",Reference="JournalNumber",Fallback="JV-{YYYY}-{NUMBER:7}";static readonly Regex Token=new(@"\{NUMBER(?::(?<length>\d{1,2}))?\}",RegexOptions.Compiled|RegexOptions.IgnoreCase);
 public async Task<AccountingParametersDto>GetAsync(long?branchId,long?warehouseId,CancellationToken ct){var s=await Sequence(branchId,ct);var p=await ResolveSettingsAsync(branchId,warehouseId,ct);return Map(p,s,branchId,warehouseId,await BranchCode(branchId,ct));}
 public async Task<AccountingParametersDto>SaveAsync(SaveAccountingParametersRequest r,CancellationToken ct){Validate(r);await ValidateRefs(r,ct);await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var s=await db.NumberSequences.FirstOrDefaultAsync(x=>x.Module==Module&&x.Reference==Reference&&x.BranchId==r.BranchId,ct);if(s is null){s=new NumberSequence{Module=Module,Reference=Reference,BranchId=r.BranchId};db.Add(s);}ApplySequence(s,r);var p=await db.AccountingParameterSettings.FirstOrDefaultAsync(x=>x.BranchId==r.BranchId&&x.WarehouseId==r.WarehouseId,ct);if(p is null){p=new AccountingParameterSettings{BranchId=r.BranchId,WarehouseId=r.WarehouseId};db.Add(p);}Apply(p,r);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Map(p,s,r.BranchId,r.WarehouseId,await BranchCode(r.BranchId,ct));}
 public async Task<AccountingParameterSettings>ResolveSettingsAsync(long?branchId,long?warehouseId,CancellationToken ct){if(!branchId.HasValue&&warehouseId.HasValue)branchId=await db.Warehouses.AsNoTracking().Where(x=>x.Id==warehouseId).Select(x=>(long?)x.BranchId).FirstOrDefaultAsync(ct);return await db.AccountingParameterSettings.AsNoTracking().Where(x=>(x.BranchId==branchId||x.BranchId==null)&&(x.WarehouseId==warehouseId||x.WarehouseId==null)).OrderByDescending(x=>x.WarehouseId.HasValue).ThenByDescending(x=>x.BranchId.HasValue).FirstOrDefaultAsync(ct)??new AccountingParameterSettings{BranchId=branchId,WarehouseId=warehouseId};}
 public Task<AccountingParameterSettings>ResolveCurrentSettingsAsync(CancellationToken ct){var claim=http.HttpContext?.User.FindFirstValue("branchId");return ResolveSettingsAsync(long.TryParse(claim,out var branchId)?branchId:null,null,ct);}
 public async Task<string>ResolveJournalNumberAsync(string?requested,long?branchId,CancellationToken ct){var s=await Sequence(branchId,ct);var manual=requested?.Trim().ToUpperInvariant();if(!string.IsNullOrWhiteSpace(manual)){if(s.IsAutomatic&&!s.AllowManual)throw new InvalidOperationException("Manual journal number is disabled by accounting parameters.");return manual;}if(!s.IsAutomatic)throw new InvalidOperationException("Journal number is required because automatic numbering is disabled.");return Format(s.Format,await Consume(s,ct),await BranchCode(branchId,ct));}
 static AccountingParametersDto Map(AccountingParameterSettings p,NumberSequence s,long?branchId,long?warehouseId,string branch)=>new(branchId,warehouseId,s.IsAutomatic,s.AllowManual,s.Format,s.CurrentNumber,s.IncrementBy,s.MinimumNumber,s.MaximumNumber,p.DefaultCurrencyCode,p.DefaultExchangeRate,p.MonetaryDecimalPlaces,p.JournalBalanceTolerance,p.RequireOpenFiscalPeriod,p.AllowBackdatedJournal,p.AllowFutureDatedJournal,p.AutoPostManualJournals,p.RequirePostingAccount,p.RequireJournalDescription,p.PreventDuplicateSourceDocument,(int)p.DefaultInventoryValuationMethod,p.RequireInventoryPostingProfile,p.CreateCostLayersOnReceipt,p.AllowNegativeInventoryValue,p.CostDecimalPlaces,p.CostCloseTolerance,p.RequireApprovalBeforeCostClose,p.AllowCostCloseReopen,p.AutoCloseInventoryWithPeriod,p.IncludeLandedCostAdjustments,Format(s.Format,s.CurrentNumber,branch));
 static void Apply(AccountingParameterSettings p,SaveAccountingParametersRequest r){p.DefaultCurrencyCode=r.DefaultCurrencyCode.Trim().ToUpperInvariant();p.DefaultExchangeRate=r.DefaultExchangeRate;p.MonetaryDecimalPlaces=r.MonetaryDecimalPlaces;p.JournalBalanceTolerance=r.JournalBalanceTolerance;p.RequireOpenFiscalPeriod=r.RequireOpenFiscalPeriod;p.AllowBackdatedJournal=r.AllowBackdatedJournal;p.AllowFutureDatedJournal=r.AllowFutureDatedJournal;p.AutoPostManualJournals=r.AutoPostManualJournals;p.RequirePostingAccount=r.RequirePostingAccount;p.RequireJournalDescription=r.RequireJournalDescription;p.PreventDuplicateSourceDocument=r.PreventDuplicateSourceDocument;p.DefaultInventoryValuationMethod=(InventoryValuationMethod)r.DefaultInventoryValuationMethod;p.RequireInventoryPostingProfile=r.RequireInventoryPostingProfile;p.CreateCostLayersOnReceipt=r.CreateCostLayersOnReceipt;p.AllowNegativeInventoryValue=r.AllowNegativeInventoryValue;p.CostDecimalPlaces=r.CostDecimalPlaces;p.CostCloseTolerance=r.CostCloseTolerance;p.RequireApprovalBeforeCostClose=r.RequireApprovalBeforeCostClose;p.AllowCostCloseReopen=r.AllowCostCloseReopen;p.AutoCloseInventoryWithPeriod=r.AutoCloseInventoryWithPeriod;p.IncludeLandedCostAdjustments=r.IncludeLandedCostAdjustments;}
 static void ApplySequence(NumberSequence s,SaveAccountingParametersRequest r){s.Format=r.JournalFormat.Trim();s.CurrentNumber=r.JournalNextNumber;s.IncrementBy=r.JournalIncrementBy;s.MinimumNumber=r.JournalMinimumNumber;s.MaximumNumber=r.JournalMaximumNumber;s.IsAutomatic=r.JournalIsAutomatic;s.AllowManual=r.JournalAllowManual;s.IsActive=true;}
 static void Validate(SaveAccountingParametersRequest r){if(!Token.IsMatch(r.JournalFormat)||r.JournalFormat.Length>120||Format(r.JournalFormat,r.JournalNextNumber,"0").Length>40)throw new ArgumentException("Journal number mask is invalid or generates more than 40 characters.");if(r.JournalIncrementBy<1||r.JournalMinimumNumber<0||r.JournalNextNumber<r.JournalMinimumNumber||r.JournalMaximumNumber<r.JournalNextNumber)throw new ArgumentException("Journal number range is invalid.");if(string.IsNullOrWhiteSpace(r.DefaultCurrencyCode)||r.DefaultCurrencyCode.Trim().Length!=3||r.DefaultExchangeRate<=0)throw new ArgumentException("Currency or exchange rate is invalid.");if(r.MonetaryDecimalPlaces is <2 or >8||r.CostDecimalPlaces is <2 or >8||r.JournalBalanceTolerance<0||r.CostCloseTolerance<0)throw new ArgumentException("Decimal places or tolerances are invalid.");if(!Enum.IsDefined(typeof(InventoryValuationMethod),r.DefaultInventoryValuationMethod))throw new ArgumentException("Inventory valuation method is invalid.");}
 async Task ValidateRefs(SaveAccountingParametersRequest r,CancellationToken ct){if(r.BranchId.HasValue&&!await db.Branches.AnyAsync(x=>x.Id==r.BranchId&&x.IsActive,ct))throw new ArgumentException("Selected branch is not active.");if(r.WarehouseId.HasValue&&!await db.Warehouses.AnyAsync(x=>x.Id==r.WarehouseId&&x.IsActive&&(!r.BranchId.HasValue||x.BranchId==r.BranchId),ct))throw new ArgumentException("Selected warehouse is not active or does not belong to the selected branch.");}
 async Task<NumberSequence>Sequence(long?branchId,CancellationToken ct)=>await db.NumberSequences.AsNoTracking().Where(x=>x.Module==Module&&x.Reference==Reference&&x.IsActive&&(x.BranchId==branchId||x.BranchId==null)).OrderByDescending(x=>x.BranchId.HasValue).FirstOrDefaultAsync(ct)??new NumberSequence{Module=Module,Reference=Reference,BranchId=branchId,Format=Fallback,CurrentNumber=1,IncrementBy=1,MinimumNumber=1,MaximumNumber=999999999,IsAutomatic=true,AllowManual=true};
 async Task<long>Consume(NumberSequence s,CancellationToken ct){var stored=await db.NumberSequences.FirstOrDefaultAsync(x=>x.Module==Module&&x.Reference==Reference&&x.BranchId==s.BranchId,ct);if(stored is null){stored=new NumberSequence{Module=Module,Reference=Reference,BranchId=s.BranchId,Format=s.Format,CurrentNumber=s.CurrentNumber,IncrementBy=s.IncrementBy,MinimumNumber=s.MinimumNumber,MaximumNumber=s.MaximumNumber,IsAutomatic=s.IsAutomatic,AllowManual=s.AllowManual,IsActive=true};db.Add(stored);await db.SaveChangesAsync(ct);}var c=db.Database.GetDbConnection();if(c.State!=ConnectionState.Open)await c.OpenAsync(ct);await using var cmd=c.CreateCommand();cmd.Transaction=db.Database.CurrentTransaction?.GetDbTransaction();cmd.CommandText="UPDATE RII_NUMBER_SEQUENCES WITH (UPDLOCK, ROWLOCK) SET CurrentNumber=CurrentNumber+IncrementBy,UpdatedAt=SYSUTCDATETIME() OUTPUT DELETED.CurrentNumber WHERE Id=@id AND IsActive=1 AND CurrentNumber<=MaximumNumber";var q=cmd.CreateParameter();q.ParameterName="@id";q.Value=stored.Id;cmd.Parameters.Add(q);var value=await cmd.ExecuteScalarAsync(ct);return value is null||value==DBNull.Value?throw new InvalidOperationException("Journal number sequence could not be consumed."):Convert.ToInt64(value);}
 async Task<string>BranchCode(long?id,CancellationToken ct)=>id.HasValue?await db.Branches.AsNoTracking().Where(x=>x.Id==id).Select(x=>x.Code).FirstOrDefaultAsync(ct)??"0":"0";static string Format(string f,long n,string branch){var result=f.Replace("{BRANCH}",branch,StringComparison.OrdinalIgnoreCase).Replace("{YYYY}",DateTime.UtcNow.ToString("yyyy"),StringComparison.OrdinalIgnoreCase).Replace("{YY}",DateTime.UtcNow.ToString("yy"),StringComparison.OrdinalIgnoreCase).Replace("{MM}",DateTime.UtcNow.ToString("MM"),StringComparison.OrdinalIgnoreCase);return Token.Replace(result,m=>n.ToString().PadLeft(Math.Clamp(int.TryParse(m.Groups["length"].Value,out var l)?l:1,1,18),'0'));}
}
