using Microsoft.EntityFrameworkCore;using Microsoft.EntityFrameworkCore.Metadata.Builders;using verii_metivon_api.Modules.Inventory.Domain.Entities;
namespace verii_metivon_api.Modules.Inventory.Infrastructure.Persistence.Configurations;
public sealed class InventoryStatusConfiguration:IEntityTypeConfiguration<InventoryStatus>{public void Configure(EntityTypeBuilder<InventoryStatus>b){b.ToTable("RII_INVENTORY_STATUSES");b.HasIndex(x=>x.Code).IsUnique();}}
public sealed class InventoryLotConfiguration:IEntityTypeConfiguration<InventoryLot>{public void Configure(EntityTypeBuilder<InventoryLot>b){b.ToTable("RII_INVENTORY_LOTS");b.HasIndex(x=>new{x.ProductId,x.LotNumber}).IsUnique();b.Property(x=>x.LotNumber).HasMaxLength(80).IsRequired();}}
public sealed class InventorySerialConfiguration:IEntityTypeConfiguration<InventorySerial>{public void Configure(EntityTypeBuilder<InventorySerial>b){b.ToTable("RII_INVENTORY_SERIALS");b.HasIndex(x=>new{x.ProductId,x.SerialNumber}).IsUnique();b.Property(x=>x.SerialNumber).HasMaxLength(120).IsRequired();}}
public sealed class InventoryTransactionConfiguration:IEntityTypeConfiguration<InventoryTransaction>{public void Configure(EntityTypeBuilder<InventoryTransaction>b){b.ToTable("RII_INVENTORY_TRANSACTIONS");b.HasIndex(x=>x.IdempotencyKey).IsUnique();b.HasIndex(x=>x.PostingId);b.HasIndex(x=>new{x.DocumentType,x.DocumentId});b.HasIndex(x=>new{x.ProductId,x.WarehouseId,x.StorageLocationId,x.PostingDate});b.Property(x=>x.Quantity).HasPrecision(24,8);b.Property(x=>x.BaseQuantity).HasPrecision(24,8);b.Property(x=>x.UnitCost).HasPrecision(24,8);b.Property(x=>x.TotalCost).HasPrecision(24,8);b.Property(x=>x.IdempotencyKey).HasMaxLength(160).IsRequired();b.Property(x=>x.DocumentType).HasMaxLength(40).IsRequired();b.Property(x=>x.DocumentNumber).HasMaxLength(60).IsRequired();b.HasOne(x=>x.ReversalOf).WithMany().HasForeignKey(x=>x.ReversalOfId).OnDelete(DeleteBehavior.Restrict);}}
public sealed class InventoryBalanceConfiguration:IEntityTypeConfiguration<InventoryBalance>{public void Configure(EntityTypeBuilder<InventoryBalance>b){b.ToTable("RII_INVENTORY_BALANCES",t=>t.HasCheckConstraint("CK_RII_INVENTORY_BALANCES_RESERVED","[ReservedQuantity] >= 0"));b.HasIndex(x=>new{x.ProductId,x.WarehouseId,x.StorageLocationId,x.InventoryStatusId,x.InventoryLotId,x.InventorySerialId}).IsUnique();b.Property(x=>x.PhysicalQuantity).HasPrecision(24,8);b.Property(x=>x.ReservedQuantity).HasPrecision(24,8);b.Property(x=>x.AvailableQuantity).HasPrecision(24,8);b.Property(x=>x.InventoryValue).HasPrecision(24,8);b.Property(x=>x.RowVersion).IsRowVersion();b.HasOne<verii_metivon_api.Modules.Products.Domain.Entities.Product>().WithMany().HasForeignKey(x=>x.ProductId).OnDelete(DeleteBehavior.Restrict);b.HasOne<verii_metivon_api.Modules.Warehouses.Domain.Entities.Warehouse>().WithMany().HasForeignKey(x=>x.WarehouseId).OnDelete(DeleteBehavior.Restrict);b.HasOne<verii_metivon_api.Modules.Warehouses.Domain.Entities.StorageLocation>().WithMany().HasForeignKey(x=>x.StorageLocationId).OnDelete(DeleteBehavior.Restrict);b.HasOne<InventoryStatus>().WithMany().HasForeignKey(x=>x.InventoryStatusId).OnDelete(DeleteBehavior.Restrict);b.HasOne<InventoryLot>().WithMany().HasForeignKey(x=>x.InventoryLotId).OnDelete(DeleteBehavior.Restrict);b.HasOne<InventorySerial>().WithMany().HasForeignKey(x=>x.InventorySerialId).OnDelete(DeleteBehavior.Restrict);}}
public sealed class InventoryReservationConfiguration:IEntityTypeConfiguration<InventoryReservation>{public void Configure(EntityTypeBuilder<InventoryReservation>b){b.ToTable("RII_INVENTORY_RESERVATIONS");b.HasIndex(x=>x.ReservationNumber).IsUnique();b.HasIndex(x=>new{x.SourceType,x.SourceId,x.SourceLineId});b.Property(x=>x.Quantity).HasPrecision(24,8);b.Property(x=>x.ConsumedQuantity).HasPrecision(24,8);}}
public sealed class InventoryCostLayerConfiguration:IEntityTypeConfiguration<InventoryCostLayer>{public void Configure(EntityTypeBuilder<InventoryCostLayer>b){b.ToTable("RII_INVENTORY_COST_LAYERS");b.HasIndex(x=>new{x.ProductId,x.WarehouseId,x.Status,x.ReceiptDate});b.Property(x=>x.OriginalQuantity).HasPrecision(24,8);b.Property(x=>x.RemainingQuantity).HasPrecision(24,8);b.Property(x=>x.UnitCost).HasPrecision(24,8);}}
public sealed class InventoryTraceabilityParameterSettingsConfiguration:IEntityTypeConfiguration<InventoryTraceabilityParameterSettings>{public void Configure(EntityTypeBuilder<InventoryTraceabilityParameterSettings>b){b.ToTable("RII_INVENTORY_TRACEABILITY_PARAMETERS",t=>{t.HasCheckConstraint("CK_RII_TRACEABILITY_SHELF_LIFE","[MinimumRemainingShelfLifeDays] >= 0 AND [MinimumRemainingShelfLifePercent] >= 0 AND [MinimumRemainingShelfLifePercent] <= 100 AND [ExpiryWarningDays] >= 0");t.HasCheckConstraint("CK_RII_TRACEABILITY_LABEL_COPIES","[DefaultLabelCopies] >= 1 AND [DefaultLabelCopies] <= 100");});b.HasKey(x=>x.Id);b.HasQueryFilter(x=>!x.IsDeleted);b.HasIndex(x=>new{x.BranchId,x.WarehouseId}).IsUnique().HasFilter("[IsDeleted] = 0");b.Property(x=>x.MinimumRemainingShelfLifePercent).HasPrecision(9,6);b.Property(x=>x.RowVersion).IsRowVersion();b.HasOne(x=>x.Branch).WithMany().HasForeignKey(x=>x.BranchId).OnDelete(DeleteBehavior.Restrict);b.HasOne(x=>x.Warehouse).WithMany().HasForeignKey(x=>x.WarehouseId).OnDelete(DeleteBehavior.Restrict);}}
