using System.Data;using System.Text.RegularExpressions;using Microsoft.EntityFrameworkCore;using Microsoft.EntityFrameworkCore.Storage;using verii_metivon_api.Core.Persistence;
using verii_metivon_api.Core.Domain;using verii_metivon_api.Modules.Parameters.Domain.Entities;using verii_metivon_api.Modules.Shipping.Domain.Entities;
namespace verii_metivon_api.Modules.Shipping.Application.Parameters;
public sealed record ShippingParametersDto(long?BranchId,long?WarehouseId,bool ShipmentIsAutomatic,bool ShipmentAllowManual,string ShipmentFormat,long ShipmentNextNumber,int ShipmentIncrementBy,long ShipmentMinimumNumber,long ShipmentMaximumNumber,bool DeliveryNoteIsAutomatic,bool DeliveryNoteAllowManual,string DeliveryNoteFormat,long DeliveryNoteNextNumber,int DeliveryNoteIncrementBy,long DeliveryNoteMinimumNumber,long DeliveryNoteMaximumNumber,bool AllowPartialShipment,bool RequireFullReservation,bool RequirePackedBeforeShipment,bool AutoMarkPackedOnCreate,bool AllowPastShipmentDate,bool RequireCarrierName,bool RequireVehiclePlate,bool RequireDriverName,bool RequireTrackingNumber,int MaximumLinesPerShipment,bool RequireLotForLotTracked,bool RequireSerialForSerialTracked,bool AutoCreateDeliveryNote,string DeliveryNoteScenario,int DefaultDeliveryNoteStatus,long InventoryCurrencyId,string InventoryCurrencyCode,string ShipmentPreview,string DeliveryNotePreview);
public sealed record SaveShippingParametersRequest(long?BranchId,long?WarehouseId,bool ShipmentIsAutomatic,bool ShipmentAllowManual,string ShipmentFormat,long ShipmentNextNumber,int ShipmentIncrementBy,long ShipmentMinimumNumber,long ShipmentMaximumNumber,bool DeliveryNoteIsAutomatic,bool DeliveryNoteAllowManual,string DeliveryNoteFormat,long DeliveryNoteNextNumber,int DeliveryNoteIncrementBy,long DeliveryNoteMinimumNumber,long DeliveryNoteMaximumNumber,bool AllowPartialShipment,bool RequireFullReservation,bool RequirePackedBeforeShipment,bool AutoMarkPackedOnCreate,bool AllowPastShipmentDate,bool RequireCarrierName,bool RequireVehiclePlate,bool RequireDriverName,bool RequireTrackingNumber,int MaximumLinesPerShipment,bool RequireLotForLotTracked,bool RequireSerialForSerialTracked,bool AutoCreateDeliveryNote,string DeliveryNoteScenario,int DefaultDeliveryNoteStatus,long InventoryCurrencyId);
public interface IShippingParameterService{Task<ShippingParametersDto>GetAsync(long?branchId,long?warehouseId,CancellationToken ct);Task<ShippingParametersDto>SaveAsync(SaveShippingParametersRequest r,CancellationToken ct);Task<ShippingParameterSettings>ResolveSettingsAsync(long?branchId,long?warehouseId,CancellationToken ct);Task<string>ResolveShipmentNumberAsync(string?requested,long?branchId,CancellationToken ct);Task<string>ResolveDeliveryNoteNumberAsync(long?branchId,CancellationToken ct);}
public sealed class ShippingParameterService(MetivonDbContext db):IShippingParameterService
{
 const string Module="Shipping",ShipmentRef="ShipmentNumber",DeliveryRef="DeliveryNoteNumber";static readonly Regex Token=new(@"\{NUMBER(?::(?<length>\d{1,2}))?\}",RegexOptions.Compiled|RegexOptions.IgnoreCase);
 public async Task<ShippingParametersDto>GetAsync(long?branchId,long?warehouseId,CancellationToken ct){var shipment=await Sequence(ShipmentRef,branchId,"SH-{YYYY}-{NUMBER:6}",ct);var delivery=await Sequence(DeliveryRef,branchId,"DN-{YYYY}-{NUMBER:6}",ct);var settings=await ResolveSettingsAsync(branchId,warehouseId,ct);await EnsureCurrency(settings,ct);var branch=await BranchCode(branchId,ct);return new(branchId,warehouseId,shipment.IsAutomatic,shipment.AllowManual,shipment.Format,shipment.CurrentNumber,shipment.IncrementBy,shipment.MinimumNumber,shipment.MaximumNumber,delivery.IsAutomatic,delivery.AllowManual,delivery.Format,delivery.CurrentNumber,delivery.IncrementBy,delivery.MinimumNumber,delivery.MaximumNumber,settings.AllowPartialShipment,settings.RequireFullReservation,settings.RequirePackedBeforeShipment,settings.AutoMarkPackedOnCreate,settings.AllowPastShipmentDate,settings.RequireCarrierName,settings.RequireVehiclePlate,settings.RequireDriverName,settings.RequireTrackingNumber,settings.MaximumLinesPerShipment,settings.RequireLotForLotTracked,settings.RequireSerialForSerialTracked,settings.AutoCreateDeliveryNote,settings.DeliveryNoteScenario,(int)settings.DefaultDeliveryNoteStatus,settings.InventoryCurrencyId,settings.InventoryCurrencyCode,Format(shipment.Format,shipment.CurrentNumber,branch),Format(delivery.Format,delivery.CurrentNumber,branch));}
 public async Task<ShippingParametersDto>SaveAsync(SaveShippingParametersRequest r,CancellationToken ct){Validate(r);await ValidateRefs(r,ct);await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var shipment=await StoredSequence(ShipmentRef,r.BranchId,ct);ApplySequence(shipment,r.ShipmentFormat,r.ShipmentNextNumber,r.ShipmentIncrementBy,r.ShipmentMinimumNumber,r.ShipmentMaximumNumber,r.ShipmentIsAutomatic,r.ShipmentAllowManual);var delivery=await StoredSequence(DeliveryRef,r.BranchId,ct);ApplySequence(delivery,r.DeliveryNoteFormat,r.DeliveryNoteNextNumber,r.DeliveryNoteIncrementBy,r.DeliveryNoteMinimumNumber,r.DeliveryNoteMaximumNumber,r.DeliveryNoteIsAutomatic,r.DeliveryNoteAllowManual);var p=await db.ShippingParameterSettings.FirstOrDefaultAsync(x=>x.BranchId==r.BranchId&&x.WarehouseId==r.WarehouseId,ct);if(p is null){p=new ShippingParameterSettings{BranchId=r.BranchId,WarehouseId=r.WarehouseId};db.Add(p);}p.AllowPartialShipment=r.AllowPartialShipment;p.RequireFullReservation=r.RequireFullReservation;p.RequirePackedBeforeShipment=r.RequirePackedBeforeShipment;p.AutoMarkPackedOnCreate=r.AutoMarkPackedOnCreate;p.AllowPastShipmentDate=r.AllowPastShipmentDate;p.RequireCarrierName=r.RequireCarrierName;p.RequireVehiclePlate=r.RequireVehiclePlate;p.RequireDriverName=r.RequireDriverName;p.RequireTrackingNumber=r.RequireTrackingNumber;p.MaximumLinesPerShipment=r.MaximumLinesPerShipment;p.RequireLotForLotTracked=r.RequireLotForLotTracked;p.RequireSerialForSerialTracked=r.RequireSerialForSerialTracked;p.AutoCreateDeliveryNote=r.AutoCreateDeliveryNote;p.DeliveryNoteScenario=r.DeliveryNoteScenario.Trim().ToUpperInvariant();p.DefaultDeliveryNoteStatus=(DeliveryNoteStatus)r.DefaultDeliveryNoteStatus;var currency=await Currency(r.InventoryCurrencyId,ct);p.InventoryCurrencyId=currency.Id;p.InventoryCurrencyCode=currency.IsoCode;await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return await GetAsync(r.BranchId,r.WarehouseId,ct);}
 public async Task<ShippingParameterSettings>ResolveSettingsAsync(long?branchId,long?warehouseId,CancellationToken ct)=>await db.ShippingParameterSettings.AsNoTracking().Where(x=>(x.BranchId==branchId||x.BranchId==null)&&(x.WarehouseId==warehouseId||x.WarehouseId==null)).OrderByDescending(x=>x.WarehouseId.HasValue).ThenByDescending(x=>x.BranchId.HasValue).FirstOrDefaultAsync(ct)??new ShippingParameterSettings{BranchId=branchId,WarehouseId=warehouseId};
 public Task<string>ResolveShipmentNumberAsync(string?requested,long?branchId,CancellationToken ct)=>ResolveNumber(ShipmentRef,"SH-{YYYY}-{NUMBER:6}",requested,branchId,ct);
 public Task<string>ResolveDeliveryNoteNumberAsync(long?branchId,CancellationToken ct)=>ResolveNumber(DeliveryRef,"DN-{YYYY}-{NUMBER:6}",null,branchId,ct);
 async Task<string>ResolveNumber(string reference,string fallback,string?requested,long?branchId,CancellationToken ct){var s=await Sequence(reference,branchId,fallback,ct);var manual=requested?.Trim().ToUpperInvariant();if(!string.IsNullOrWhiteSpace(manual)){if(s.IsAutomatic&&!s.AllowManual)throw new InvalidOperationException("Manual document number is disabled by shipping parameters.");return manual;}if(!s.IsAutomatic)throw new InvalidOperationException("Document number is required because automatic numbering is disabled.");return Format(s.Format,await Consume(s,ct),await BranchCode(branchId,ct));}
 async Task<NumberSequence>Sequence(string reference,long?branchId,string fallback,CancellationToken ct)=>await db.NumberSequences.AsNoTracking().Where(x=>x.Module==Module&&x.Reference==reference&&x.IsActive&&(x.BranchId==branchId||x.BranchId==null)).OrderByDescending(x=>x.BranchId.HasValue).FirstOrDefaultAsync(ct)??new NumberSequence{Module=Module,Reference=reference,BranchId=branchId,Format=fallback,CurrentNumber=1,IncrementBy=1,MinimumNumber=1,MaximumNumber=999999999,IsAutomatic=true,AllowManual=true};
 async Task<NumberSequence>StoredSequence(string reference,long?branchId,CancellationToken ct){var s=await db.NumberSequences.FirstOrDefaultAsync(x=>x.Module==Module&&x.Reference==reference&&x.BranchId==branchId,ct);if(s is null){s=new NumberSequence{Module=Module,Reference=reference,BranchId=branchId};db.Add(s);}return s;}
 static void ApplySequence(NumberSequence s,string f,long next,int increment,long min,long max,bool automatic,bool manual){s.Format=f.Trim();s.CurrentNumber=next;s.IncrementBy=increment;s.MinimumNumber=min;s.MaximumNumber=max;s.IsAutomatic=automatic;s.AllowManual=manual;s.IsActive=true;}
 async Task ValidateRefs(SaveShippingParametersRequest r,CancellationToken ct){if(r.BranchId.HasValue&&!await db.Branches.AnyAsync(x=>x.Id==r.BranchId&&x.IsActive,ct))throw new ArgumentException("Selected branch is not active.");if(r.WarehouseId.HasValue&&!await db.Warehouses.AnyAsync(x=>x.Id==r.WarehouseId&&x.IsActive&&(!r.BranchId.HasValue||x.BranchId==r.BranchId),ct))throw new ArgumentException("Selected warehouse is not active or does not belong to the selected branch.");}
 static void Validate(SaveShippingParametersRequest r){ValidateSequence(r.ShipmentFormat,r.ShipmentNextNumber,r.ShipmentIncrementBy,r.ShipmentMinimumNumber,r.ShipmentMaximumNumber);ValidateSequence(r.DeliveryNoteFormat,r.DeliveryNoteNextNumber,r.DeliveryNoteIncrementBy,r.DeliveryNoteMinimumNumber,r.DeliveryNoteMaximumNumber);if(r.MaximumLinesPerShipment is <1 or >10000)throw new ArgumentException("Maximum shipment line count is invalid.");if(string.IsNullOrWhiteSpace(r.DeliveryNoteScenario)||r.DeliveryNoteScenario.Trim().Length>30)throw new ArgumentException("Delivery note scenario is required and cannot exceed 30 characters.");if(!Enum.IsDefined(typeof(DeliveryNoteStatus),r.DefaultDeliveryNoteStatus))throw new ArgumentException("Delivery note status is invalid.");if(r.InventoryCurrencyId<=0)throw new ArgumentException("A defined inventory currency is required.");if(r.AutoMarkPackedOnCreate&&!r.RequirePackedBeforeShipment)throw new ArgumentException("Automatic packing requires packed-before-shipment control.");}
 async Task EnsureCurrency(ShippingParameterSettings p,CancellationToken ct){if(p.InventoryCurrencyId>0)return;var id=await db.Currencies.AsNoTracking().Where(x=>x.IsActive).OrderByDescending(x=>x.IsDefault).ThenBy(x=>x.Id).Select(x=>x.Id).FirstOrDefaultAsync(ct);var currency=await Currency(id,ct);p.InventoryCurrencyId=currency.Id;p.InventoryCurrencyCode=currency.IsoCode;}
 async Task<Currency>Currency(long id,CancellationToken ct)=>await db.Currencies.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id&&x.IsActive,ct)??throw new ArgumentException("Selected currency is not active.");
 static void ValidateSequence(string f,long next,int increment,long min,long max){if(!Token.IsMatch(f)||f.Length>120||Format(f,next,"0").Length>40)throw new ArgumentException("Document mask is invalid or generates more than 40 characters.");if(increment<1||min<0||next<min||max<next)throw new ArgumentException("Document number range is invalid.");}
 async Task<string>BranchCode(long?id,CancellationToken ct)=>id.HasValue?await db.Branches.AsNoTracking().Where(x=>x.Id==id).Select(x=>x.Code).FirstOrDefaultAsync(ct)??"0":"0";
 async Task<long>Consume(NumberSequence s,CancellationToken ct){if(s.Id==0){db.Add(s);await db.SaveChangesAsync(ct);}var c=db.Database.GetDbConnection();if(c.State!=ConnectionState.Open)await c.OpenAsync(ct);await using var cmd=c.CreateCommand();cmd.Transaction=db.Database.CurrentTransaction?.GetDbTransaction();cmd.CommandText="UPDATE RII_NUMBER_SEQUENCES WITH (UPDLOCK, ROWLOCK) SET CurrentNumber=CurrentNumber+IncrementBy,UpdatedAt=SYSUTCDATETIME() OUTPUT DELETED.CurrentNumber WHERE Id=@id AND IsActive=1 AND CurrentNumber<=MaximumNumber";var p=cmd.CreateParameter();p.ParameterName="@id";p.Value=s.Id;cmd.Parameters.Add(p);var value=await cmd.ExecuteScalarAsync(ct);return value is null||value==DBNull.Value?throw new InvalidOperationException("Document number sequence could not be consumed."):Convert.ToInt64(value);}
 static string Format(string f,long n,string branch){var result=f.Replace("{BRANCH}",branch,StringComparison.OrdinalIgnoreCase).Replace("{YYYY}",DateTime.UtcNow.ToString("yyyy"),StringComparison.OrdinalIgnoreCase).Replace("{YY}",DateTime.UtcNow.ToString("yy"),StringComparison.OrdinalIgnoreCase).Replace("{MM}",DateTime.UtcNow.ToString("MM"),StringComparison.OrdinalIgnoreCase);return Token.Replace(result,m=>n.ToString().PadLeft(Math.Clamp(int.TryParse(m.Groups["length"].Value,out var l)?l:1,1,18),'0'));}
}
