using verii_metivon_api.Core.Auth;using verii_metivon_api.Core.Paging;using verii_metivon_api.Modules.Inventory.Domain.Enums;
namespace verii_metivon_api.Modules.Inventory.Application.Services;
public sealed class InventoryTransactionQuery:PagedQuery{public long? ProductId{get;init;}public long? WarehouseId{get;init;}public long? LocationId{get;init;}public InventoryMovementType? MovementType{get;init;}public DateTime? FromDate{get;init;}public DateTime? ToDate{get;init;}}
public sealed class InventoryBalanceQuery:PagedQuery{public long? ProductId{get;init;}public long? WarehouseId{get;init;}public long? LocationId{get;init;}public bool AvailableOnly{get;init;}}
public sealed class InventoryDashboardQuery{public long? BranchId{get;init;}public long? WarehouseId{get;init;}public int ExpiryWarningDays{get;init;}=60;}
public sealed record InventoryTransactionRow(long Id,Guid PostingId,string DocumentType,string DocumentNumber,DateTime PostingDate,string MovementType,string ProductCode,string ProductName,string WarehouseCode,string LocationCode,string? LotNumber,string? SerialNumber,decimal Quantity,decimal UnitCost,decimal TotalCost);
public sealed record InventoryBalanceRow(long Id,long ProductId,string ProductCode,string ProductName,long WarehouseId,string WarehouseCode,long LocationId,string LocationCode,string InventoryStatus,string? LotNumber,string? SerialNumber,DateOnly? ExpiryDate,decimal PhysicalQuantity,decimal ReservedQuantity,decimal AvailableQuantity,decimal InventoryValue);
public sealed record InventoryDashboardSummary(decimal PhysicalQuantity,decimal ReservedQuantity,decimal AvailableQuantity,decimal InventoryValue,int ProductCount,int WarehouseCount,int BalanceDimensionCount,int NegativeBalanceCount,int LowStockProductCount,int ExpiringLotCount);
public sealed record InventoryDashboardWarehouse(long WarehouseId,string WarehouseCode,string WarehouseName,decimal PhysicalQuantity,decimal AvailableQuantity,decimal InventoryValue);
public sealed record InventoryDashboardStatus(string StatusCode,string StatusName,decimal PhysicalQuantity,decimal AvailableQuantity,decimal InventoryValue);
public sealed record InventoryDashboardMovement(long Id,string DocumentType,string DocumentNumber,DateTime PostingDate,string MovementType,string ProductCode,string ProductName,string WarehouseCode,decimal Quantity,decimal TotalCost);
public sealed record InventoryDashboardResult(InventoryDashboardSummary Summary,IReadOnlyList<InventoryDashboardWarehouse> Warehouses,IReadOnlyList<InventoryDashboardStatus> Statuses,IReadOnlyList<InventoryDashboardMovement> RecentMovements,DateTime GeneratedAtUtc);
public sealed record PostInventoryLine(long ProductId,long UnitId,long WarehouseId,long StorageLocationId,long InventoryStatusId,long? InventoryLotId,long? InventorySerialId,decimal Quantity,decimal? UnitCost,long? DocumentLineId,string? Explanation);
public sealed record PostInventoryRequest(string IdempotencyKey,string DocumentType,long DocumentId,string DocumentNumber,DateTime PostingDate,InventoryMovementType MovementType,InventoryMovementDirection Direction,string CurrencyCode,IReadOnlyList<PostInventoryLine> Lines);
public sealed record PostInventoryResult(Guid PostingId,IReadOnlyList<long> TransactionIds);
public interface IInventoryService{Task<ApiResponse<PagedResult<InventoryTransactionRow>>>GetTransactionsAsync(InventoryTransactionQuery q,CancellationToken ct);Task<ApiResponse<PagedResult<InventoryBalanceRow>>>GetBalancesAsync(InventoryBalanceQuery q,CancellationToken ct);Task<ApiResponse<InventoryDashboardResult>>GetDashboardAsync(InventoryDashboardQuery q,CancellationToken ct);Task<ApiResponse<PostInventoryResult>>PostAsync(PostInventoryRequest r,CancellationToken ct);}
