using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using verii_metivon_api.Modules.Warehouses.Domain.Entities;

namespace verii_metivon_api.Modules.Warehouses.Infrastructure.Persistence.Configurations;

public sealed class WarehouseConfiguration : IEntityTypeConfiguration<Warehouse>
{
 public void Configure(EntityTypeBuilder<Warehouse> b){b.ToTable("RII_WAREHOUSES");b.HasIndex(x=>x.Code).IsUnique();b.Property(x=>x.Code).HasMaxLength(30).IsRequired();b.Property(x=>x.Name).HasMaxLength(150).IsRequired();b.HasOne(x=>x.Branch).WithMany().HasForeignKey(x=>x.BranchId).OnDelete(DeleteBehavior.Restrict);b.HasOne(x=>x.WarehouseType).WithMany().HasForeignKey(x=>x.WarehouseTypeId).OnDelete(DeleteBehavior.Restrict);}
}
public sealed class WarehouseTypeConfiguration:IEntityTypeConfiguration<WarehouseType>{public void Configure(EntityTypeBuilder<WarehouseType>b){b.ToTable("RII_WAREHOUSE_TYPES");b.HasIndex(x=>x.Code).IsUnique();}}
public sealed class LocationTypeConfiguration:IEntityTypeConfiguration<LocationType>{public void Configure(EntityTypeBuilder<LocationType>b){b.ToTable("RII_LOCATION_TYPES");b.HasIndex(x=>x.Code).IsUnique();}}
public sealed class WarehouseZoneConfiguration:IEntityTypeConfiguration<WarehouseZone>{public void Configure(EntityTypeBuilder<WarehouseZone>b){b.ToTable("RII_WAREHOUSE_ZONES");b.HasIndex(x=>new{x.WarehouseId,x.Code}).IsUnique();b.Property(x=>x.Code).HasMaxLength(30).IsRequired();b.Property(x=>x.Name).HasMaxLength(100).IsRequired();b.HasOne(x=>x.Warehouse).WithMany(x=>x.Zones).HasForeignKey(x=>x.WarehouseId).OnDelete(DeleteBehavior.Restrict);}}
public sealed class StorageLocationConfiguration:IEntityTypeConfiguration<StorageLocation>{public void Configure(EntityTypeBuilder<StorageLocation>b){b.ToTable("RII_STORAGE_LOCATIONS");b.HasIndex(x=>new{x.WarehouseId,x.Code}).IsUnique();b.HasIndex(x=>x.Barcode).IsUnique().HasFilter("[Barcode] IS NOT NULL");b.Property(x=>x.Code).HasMaxLength(50).IsRequired();b.HasOne(x=>x.Warehouse).WithMany().HasForeignKey(x=>x.WarehouseId).OnDelete(DeleteBehavior.Restrict);b.HasOne(x=>x.WarehouseZone).WithMany().HasForeignKey(x=>x.WarehouseZoneId).OnDelete(DeleteBehavior.Restrict);b.HasOne(x=>x.LocationType).WithMany().HasForeignKey(x=>x.LocationTypeId).OnDelete(DeleteBehavior.Restrict);b.Property(x=>x.MaximumWeight).HasPrecision(18,6);b.Property(x=>x.MaximumVolume).HasPrecision(18,6);b.Property(x=>x.MaximumQuantity).HasPrecision(18,6);}}
public sealed class WarehouseParameterSettingsConfiguration:IEntityTypeConfiguration<WarehouseParameterSettings>{public void Configure(EntityTypeBuilder<WarehouseParameterSettings>b){b.ToTable("RII_WAREHOUSE_PARAMETERS",t=>t.HasCheckConstraint("CK_RII_WAREHOUSE_PARAMETERS_LABEL_COPIES","[DefaultLabelCopies] >= 1 AND [DefaultLabelCopies] <= 100"));b.HasKey(x=>x.Id);b.HasQueryFilter(x=>!x.IsDeleted);b.HasIndex(x=>new{x.BranchId,x.WarehouseId}).IsUnique().HasFilter("[IsDeleted] = 0");b.Property(x=>x.LocationCodeFormat).HasMaxLength(160).IsRequired();b.Property(x=>x.DefaultLabelCopies);b.Property(x=>x.RowVersion).IsRowVersion();b.HasOne(x=>x.Branch).WithMany().HasForeignKey(x=>x.BranchId).OnDelete(DeleteBehavior.Restrict);b.HasOne(x=>x.Warehouse).WithMany().HasForeignKey(x=>x.WarehouseId).OnDelete(DeleteBehavior.Restrict);}}
