using Microsoft.EntityFrameworkCore;using verii_metivon_api.Core.Persistence;using verii_metivon_api.Modules.Pricing.Domain.Entities;
namespace verii_metivon_api.Modules.Pricing.Application.Parameters;
public sealed record PricingParametersDto(long?BranchId,int PriceRoundingDecimals,int DiscountRoundingDecimals,int RoundingMethod,bool PreferCustomerGroupPrice,bool PreferHigherMinimumQuantity,bool PreferHigherPriceListPriority,bool FallbackToDefaultPriceList,bool AllowPriceListOverlap,bool AllowZeroPrice,bool AllowMultipleDiscounts,bool AllowFixedAmountDiscount,bool StopAtExclusiveDiscount,int MaximumDiscountRulesApplied,decimal MaximumTotalDiscountPercent);
public sealed record SavePricingParametersRequest(long?BranchId,int PriceRoundingDecimals,int DiscountRoundingDecimals,int RoundingMethod,bool PreferCustomerGroupPrice,bool PreferHigherMinimumQuantity,bool PreferHigherPriceListPriority,bool FallbackToDefaultPriceList,bool AllowPriceListOverlap,bool AllowZeroPrice,bool AllowMultipleDiscounts,bool AllowFixedAmountDiscount,bool StopAtExclusiveDiscount,int MaximumDiscountRulesApplied,decimal MaximumTotalDiscountPercent);
public interface IPricingParameterService{Task<PricingParametersDto>GetAsync(long?branchId,CancellationToken ct);Task<PricingParametersDto>SaveAsync(SavePricingParametersRequest r,CancellationToken ct);Task<PricingParameterSettings>ResolveSettingsAsync(long?branchId,CancellationToken ct);}
public sealed class PricingParameterService(MetivonDbContext db):IPricingParameterService
{
 public async Task<PricingParametersDto>GetAsync(long?branchId,CancellationToken ct){var p=await ResolveSettingsAsync(branchId,ct);return Map(branchId,p);}
 public async Task<PricingParametersDto>SaveAsync(SavePricingParametersRequest r,CancellationToken ct){Validate(r);if(r.BranchId.HasValue&&!await db.Branches.AnyAsync(x=>x.Id==r.BranchId&&x.IsActive,ct))throw new ArgumentException("Selected branch is not active.");var p=await db.PricingParameterSettings.FirstOrDefaultAsync(x=>x.BranchId==r.BranchId,ct);if(p is null){p=new PricingParameterSettings{BranchId=r.BranchId};db.Add(p);}p.PriceRoundingDecimals=r.PriceRoundingDecimals;p.DiscountRoundingDecimals=r.DiscountRoundingDecimals;p.RoundingMethod=r.RoundingMethod;p.PreferCustomerGroupPrice=r.PreferCustomerGroupPrice;p.PreferHigherMinimumQuantity=r.PreferHigherMinimumQuantity;p.PreferHigherPriceListPriority=r.PreferHigherPriceListPriority;p.FallbackToDefaultPriceList=r.FallbackToDefaultPriceList;p.AllowPriceListOverlap=r.AllowPriceListOverlap;p.AllowZeroPrice=r.AllowZeroPrice;p.AllowMultipleDiscounts=r.AllowMultipleDiscounts;p.AllowFixedAmountDiscount=r.AllowFixedAmountDiscount;p.StopAtExclusiveDiscount=r.StopAtExclusiveDiscount;p.MaximumDiscountRulesApplied=r.MaximumDiscountRulesApplied;p.MaximumTotalDiscountPercent=r.MaximumTotalDiscountPercent;await db.SaveChangesAsync(ct);return Map(r.BranchId,p);}
 public async Task<PricingParameterSettings>ResolveSettingsAsync(long?branchId,CancellationToken ct)=>await db.PricingParameterSettings.AsNoTracking().Where(x=>x.BranchId==branchId||x.BranchId==null).OrderByDescending(x=>x.BranchId.HasValue).FirstOrDefaultAsync(ct)??new PricingParameterSettings{BranchId=branchId};
 static PricingParametersDto Map(long?branchId,PricingParameterSettings p)=>new(branchId,p.PriceRoundingDecimals,p.DiscountRoundingDecimals,p.RoundingMethod,p.PreferCustomerGroupPrice,p.PreferHigherMinimumQuantity,p.PreferHigherPriceListPriority,p.FallbackToDefaultPriceList,p.AllowPriceListOverlap,p.AllowZeroPrice,p.AllowMultipleDiscounts,p.AllowFixedAmountDiscount,p.StopAtExclusiveDiscount,p.MaximumDiscountRulesApplied,p.MaximumTotalDiscountPercent);
 static void Validate(SavePricingParametersRequest r){if(r.PriceRoundingDecimals is <0 or >8||r.DiscountRoundingDecimals is <0 or >8)throw new ArgumentException("Rounding decimals must be between 0 and 8.");if(r.RoundingMethod is <0 or >3)throw new ArgumentException("Rounding method is invalid.");if(r.MaximumDiscountRulesApplied is <1 or >100)throw new ArgumentException("Maximum discount rule count is invalid.");if(r.MaximumTotalDiscountPercent is <0 or >100)throw new ArgumentException("Maximum total discount must be between 0 and 100.");}
}
