using System.Data;
using Microsoft.EntityFrameworkCore;
using verii_metivon_api.Core.Persistence;
using verii_metivon_api.Core.Domain;
using verii_metivon_api.Modules.EDocuments.Domain.Entities;

namespace verii_metivon_api.Modules.EDocuments.Application.Parameters;

public sealed record EDocumentParametersDto(long BranchId,int ProviderType,string ProviderEnvironment,string InvoiceServiceUrl,string DespatchServiceUrl,string CredentialReference,int TimeoutSeconds,int MaximumRetryCount,bool ProviderIsActive,string DefaultInvoiceScenario,string DefaultArchiveInvoiceScenario,string DefaultDespatchScenario,bool AutoQueueAfterCreate,bool RequireUblValidation,bool RequireCompanyLegalProfile,bool RequireTaxNumberValidation,bool PreventDuplicateSourceDocument,bool FallbackToEArchive,bool RequireRecipientMailboxForEInvoice,bool SendEArchiveByEmail,bool AllowManualScenario,int RetryDelayMinutes,int StatusPollingIntervalMinutes,int ArchiveRetentionYears,int MaximumXmlSizeKb,long DefaultCurrencyId,string DefaultCurrencyCode);
public sealed record SaveEDocumentParametersRequest(long BranchId,int ProviderType,string ProviderEnvironment,string InvoiceServiceUrl,string DespatchServiceUrl,string CredentialReference,int TimeoutSeconds,int MaximumRetryCount,bool ProviderIsActive,string DefaultInvoiceScenario,string DefaultArchiveInvoiceScenario,string DefaultDespatchScenario,bool AutoQueueAfterCreate,bool RequireUblValidation,bool RequireCompanyLegalProfile,bool RequireTaxNumberValidation,bool PreventDuplicateSourceDocument,bool FallbackToEArchive,bool RequireRecipientMailboxForEInvoice,bool SendEArchiveByEmail,bool AllowManualScenario,int RetryDelayMinutes,int StatusPollingIntervalMinutes,int ArchiveRetentionYears,int MaximumXmlSizeKb,long DefaultCurrencyId);

public interface IEDocumentParameterService
{
 Task<EDocumentParametersDto>GetAsync(long branchId,CancellationToken ct);
 Task<EDocumentParametersDto>SaveAsync(SaveEDocumentParametersRequest r,CancellationToken ct);
 Task<EDocumentParameterSettings>ResolveSettingsAsync(long branchId,CancellationToken ct);
 Task<EDocumentProviderConfiguration?>ResolveProviderAsync(long branchId,CancellationToken ct);
}

public sealed class EDocumentParameterService(MetivonDbContext db):IEDocumentParameterService
{
 public async Task<EDocumentParametersDto>GetAsync(long branchId,CancellationToken ct){var p=await ResolveSettingsAsync(branchId,ct);await EnsureCurrency(p,ct);var c=await db.EDocumentProviderConfigurations.AsNoTracking().FirstOrDefaultAsync(x=>x.BranchId==branchId&&x.ProviderType==p.ProviderType&&x.Environment==p.ProviderEnvironment,ct);return Map(p,c);}
 public async Task<EDocumentParametersDto>SaveAsync(SaveEDocumentParametersRequest r,CancellationToken ct)
 {
  Validate(r);if(!await db.Branches.AnyAsync(x=>x.Id==r.BranchId&&x.IsActive,ct))throw new ArgumentException("Selected branch is not active.");await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);
  var p=await db.EDocumentParameterSettings.FirstOrDefaultAsync(x=>x.BranchId==r.BranchId,ct);if(p is null){p=new EDocumentParameterSettings{BranchId=r.BranchId};db.Add(p);}Apply(p,r,await Currency(r.DefaultCurrencyId,ct));
  var provider=(EDocumentProviderType)r.ProviderType;var env=NormalizeEnvironment(r.ProviderEnvironment);var c=await db.EDocumentProviderConfigurations.FirstOrDefaultAsync(x=>x.BranchId==r.BranchId&&x.ProviderType==provider&&x.Environment==env,ct);if(c is null){c=new EDocumentProviderConfiguration{BranchId=r.BranchId,ProviderType=provider,Environment=env};db.Add(c);}c.InvoiceServiceUrl=r.InvoiceServiceUrl.Trim();c.DespatchServiceUrl=r.DespatchServiceUrl.Trim();c.CredentialReference=r.CredentialReference.Trim();c.TimeoutSeconds=r.TimeoutSeconds;c.MaximumRetryCount=r.MaximumRetryCount;c.IsActive=r.ProviderIsActive;
  await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return Map(p,c);
 }
 public async Task<EDocumentParameterSettings>ResolveSettingsAsync(long branchId,CancellationToken ct)=>await db.EDocumentParameterSettings.AsNoTracking().FirstOrDefaultAsync(x=>x.BranchId==branchId,ct)??new EDocumentParameterSettings{BranchId=branchId};
 public async Task<EDocumentProviderConfiguration?>ResolveProviderAsync(long branchId,CancellationToken ct){var p=await ResolveSettingsAsync(branchId,ct);return await db.EDocumentProviderConfigurations.AsNoTracking().FirstOrDefaultAsync(x=>x.BranchId==branchId&&x.ProviderType==p.ProviderType&&x.Environment==p.ProviderEnvironment&&x.IsActive,ct);}
 static EDocumentParametersDto Map(EDocumentParameterSettings p,EDocumentProviderConfiguration?c)=>new(p.BranchId,(int)p.ProviderType,p.ProviderEnvironment,c?.InvoiceServiceUrl??"",c?.DespatchServiceUrl??"",c?.CredentialReference??"",c?.TimeoutSeconds??60,c?.MaximumRetryCount??5,c?.IsActive??false,p.DefaultInvoiceScenario,p.DefaultArchiveInvoiceScenario,p.DefaultDespatchScenario,p.AutoQueueAfterCreate,p.RequireUblValidation,p.RequireCompanyLegalProfile,p.RequireTaxNumberValidation,p.PreventDuplicateSourceDocument,p.FallbackToEArchive,p.RequireRecipientMailboxForEInvoice,p.SendEArchiveByEmail,p.AllowManualScenario,p.RetryDelayMinutes,p.StatusPollingIntervalMinutes,p.ArchiveRetentionYears,p.MaximumXmlSizeKb,p.DefaultCurrencyId,p.DefaultCurrencyCode);
 static void Apply(EDocumentParameterSettings p,SaveEDocumentParametersRequest r,Currency currency){p.ProviderType=(EDocumentProviderType)r.ProviderType;p.ProviderEnvironment=NormalizeEnvironment(r.ProviderEnvironment);p.DefaultInvoiceScenario=Normalize(r.DefaultInvoiceScenario);p.DefaultArchiveInvoiceScenario=Normalize(r.DefaultArchiveInvoiceScenario);p.DefaultDespatchScenario=Normalize(r.DefaultDespatchScenario);p.AutoQueueAfterCreate=r.AutoQueueAfterCreate;p.RequireUblValidation=r.RequireUblValidation;p.RequireCompanyLegalProfile=r.RequireCompanyLegalProfile;p.RequireTaxNumberValidation=r.RequireTaxNumberValidation;p.PreventDuplicateSourceDocument=r.PreventDuplicateSourceDocument;p.FallbackToEArchive=r.FallbackToEArchive;p.RequireRecipientMailboxForEInvoice=r.RequireRecipientMailboxForEInvoice;p.SendEArchiveByEmail=r.SendEArchiveByEmail;p.AllowManualScenario=r.AllowManualScenario;p.RetryDelayMinutes=r.RetryDelayMinutes;p.StatusPollingIntervalMinutes=r.StatusPollingIntervalMinutes;p.ArchiveRetentionYears=r.ArchiveRetentionYears;p.MaximumXmlSizeKb=r.MaximumXmlSizeKb;p.DefaultCurrencyId=currency.Id;p.DefaultCurrencyCode=currency.IsoCode;}
 static void Validate(SaveEDocumentParametersRequest r){if(r.BranchId<=0)throw new ArgumentException("Branch is required.");if(!Enum.IsDefined(typeof(EDocumentProviderType),r.ProviderType))throw new ArgumentException("Provider type is invalid.");var env=NormalizeEnvironment(r.ProviderEnvironment);if(env is not("Test" or "Production"))throw new ArgumentException("Provider environment must be Test or Production.");if(r.ProviderIsActive&&(!ValidUrl(r.InvoiceServiceUrl)||!ValidUrl(r.DespatchServiceUrl)||string.IsNullOrWhiteSpace(r.CredentialReference)))throw new ArgumentException("Active provider requires valid invoice/despatch URLs and a credential reference.");if(r.TimeoutSeconds is <5 or >300||r.MaximumRetryCount is <0 or >20)throw new ArgumentException("Provider timeout or retry count is invalid.");foreach(var scenario in new[]{r.DefaultInvoiceScenario,r.DefaultArchiveInvoiceScenario,r.DefaultDespatchScenario})if(string.IsNullOrWhiteSpace(scenario)||scenario.Trim().Length>30)throw new ArgumentException("Document scenarios are required and cannot exceed 30 characters.");if(r.RetryDelayMinutes is <1 or >1440||r.StatusPollingIntervalMinutes is <1 or >1440||r.ArchiveRetentionYears is <1 or >20||r.MaximumXmlSizeKb is <64 or >10240)throw new ArgumentException("Queue, retention or XML size parameters are invalid.");if(r.DefaultCurrencyId<=0)throw new ArgumentException("A defined default currency is required.");}
 async Task EnsureCurrency(EDocumentParameterSettings p,CancellationToken ct){if(p.DefaultCurrencyId>0)return;var id=await db.Currencies.AsNoTracking().Where(x=>x.IsActive).OrderByDescending(x=>x.IsDefault).ThenBy(x=>x.Id).Select(x=>x.Id).FirstOrDefaultAsync(ct);var currency=await Currency(id,ct);p.DefaultCurrencyId=currency.Id;p.DefaultCurrencyCode=currency.IsoCode;}
 async Task<Currency>Currency(long id,CancellationToken ct)=>await db.Currencies.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id&&x.IsActive,ct)??throw new ArgumentException("Selected currency is not active.");
 static bool ValidUrl(string value)=>Uri.TryCreate(value,UriKind.Absolute,out var uri)&&uri.Scheme is "http" or "https";static string Normalize(string value)=>value.Trim().ToUpperInvariant();static string NormalizeEnvironment(string value)=>string.Equals(value.Trim(),"Production",StringComparison.OrdinalIgnoreCase)?"Production":"Test";
}
