using Microsoft.EntityFrameworkCore;using verii_metivon_api.Core.Auth;using verii_metivon_api.Core.Paging;using verii_metivon_api.Core.Persistence;using verii_metivon_api.Core.UnitOfWork;using verii_metivon_api.Modules.Inventory.Domain.Entities;using verii_metivon_api.Modules.Inventory.Domain.Enums;using verii_metivon_api.Modules.Pricing.Application.Services;using verii_metivon_api.Modules.Sales.Application.Parameters;using verii_metivon_api.Modules.Sales.Domain.Entities;
using verii_metivon_api.Modules.NumberSeries.Application;
namespace verii_metivon_api.Modules.Sales.Application.Services;
public sealed class SalesOrderQuery:PagedQuery{public long?CustomerId{get;init;}public long?WarehouseId{get;init;}public SalesOrderStatus?Status{get;init;}}
public sealed record SalesOrderRow(long Id,string OrderNumber,string CustomerCode,string CustomerName,string WarehouseCode,DateOnly OrderDate,DateOnly?ShipmentDate,string Currency,decimal GrandTotal,string Status);
public sealed record CreateSalesLine(long ProductId,long UnitId,long StorageLocationId,long InventoryStatusId,long?InventoryLotId,long?InventorySerialId,decimal Quantity,decimal?UnitPrice,decimal TaxRate,string?Notes);
public sealed record CreateSalesOrderRequest(string?OrderNumber,long?NumberSeriesId,long BranchId,long CustomerId,long?CustomerGroupId,long CurrencyId,long PaymentTermId,long WarehouseId,DateOnly OrderDate,DateOnly?RequestedShipmentDate,string?CustomerReference,decimal ExchangeRate,IReadOnlyList<CreateSalesLine>Lines);
public interface ISalesOrderService{Task<ApiResponse<PagedResult<SalesOrderRow>>>GetPagedAsync(SalesOrderQuery q,CancellationToken ct);Task<ApiResponse<object>>CreateAsync(CreateSalesOrderRequest r,CancellationToken ct);Task<ApiResponse<object>>ConfirmAsync(long id,CancellationToken ct);}

public sealed class SalesOrderService(IUnitOfWork u,IPricingService pricing,ISalesOrderParameterService parameters,MetivonDbContext db,INumberSeriesService numberSeries):ISalesOrderService
{
 public async Task<ApiResponse<PagedResult<SalesOrderRow>>>GetPagedAsync(SalesOrderQuery q,CancellationToken ct){var x=u.Repository<SalesOrder>().Query().Include(v=>v.Customer).Include(v=>v.Warehouse).Include(v=>v.Currency).AsQueryable();if(q.CustomerId.HasValue)x=x.Where(v=>v.CustomerId==q.CustomerId);if(q.WarehouseId.HasValue)x=x.Where(v=>v.WarehouseId==q.WarehouseId);if(q.Status.HasValue)x=x.Where(v=>v.Status==q.Status);if(!string.IsNullOrWhiteSpace(q.Search)){var s=q.Search.Trim();x=x.Where(v=>v.OrderNumber.Contains(s)||v.Customer.Code.Contains(s)||v.Customer.Name.Contains(s));}x=x.ApplyPagedFilters(q);var total=await x.CountAsync(ct);var rows=await x.OrderByDescending(v=>v.OrderDate).ThenByDescending(v=>v.Id).Skip((q.NormalizedPageNumber-1)*q.NormalizedPageSize).Take(q.NormalizedPageSize).Select(v=>new SalesOrderRow(v.Id,v.OrderNumber,v.Customer.Code,v.Customer.Name,v.Warehouse.Code,v.OrderDate,v.RequestedShipmentDate,v.Currency.Code,v.GrandTotal,v.Status.ToString())).ToListAsync(ct);return ApiResponse<PagedResult<SalesOrderRow>>.Ok(new(rows,q.NormalizedPageNumber,q.NormalizedPageSize,total));}
 public async Task<ApiResponse<object>>CreateAsync(CreateSalesOrderRequest r,CancellationToken ct)
 {
  var p=await parameters.ResolveSettingsAsync(r.BranchId,r.WarehouseId,ct);if(r.Lines.Count==0)return ApiResponse<object>.Error("Lines are required.",400);if(r.Lines.Count>p.MaximumLinesPerOrder)return ApiResponse<object>.Error($"Sales order cannot exceed {p.MaximumLinesPerOrder} lines.",400);if(!p.AllowPastOrderDate&&r.OrderDate<DateOnly.FromDateTime(DateTime.UtcNow))return ApiResponse<object>.Error("Past sales order date is disabled by sales parameters.",400);if(p.RequireCustomerReference&&string.IsNullOrWhiteSpace(r.CustomerReference))return ApiResponse<object>.Error("Customer reference is required.",400);if(p.RequireActiveCustomer&&!await db.BusinessPartners.AsNoTracking().AnyAsync(x=>x.Id==r.CustomerId&&x.IsActive,ct))return ApiResponse<object>.Error("Customer is not active or could not be found.",400);var shipmentDate=r.RequestedShipmentDate??r.OrderDate.AddDays(p.DefaultShipmentLeadTimeDays);if(p.RequireRequestedShipmentDate&&!r.RequestedShipmentDate.HasValue&&p.DefaultShipmentLeadTimeDays==0)return ApiResponse<object>.Error("Requested shipment date is required.",400);ReservedNumber? reserved=null;string number;try{if(string.IsNullOrWhiteSpace(r.OrderNumber)){reserved=await numberSeries.ReserveAsync(new("Sales","SalesOrderNumber",r.NumberSeriesId,r.BranchId,r.WarehouseId,null,r.CustomerId,null,null,r.OrderDate,"SalesOrder"),ct);number=reserved.DocumentNumber;}else number=await parameters.ResolveOrderNumberAsync(r.OrderNumber,r.BranchId,ct);}catch(InvalidOperationException exception){return ApiResponse<object>.Error(exception.Message,400);}if(await u.Repository<SalesOrder>().ExistsAsync(x=>x.OrderNumber==number,ct))return ApiResponse<object>.Error("Sales order number already exists.",409);
  var e=new SalesOrder{OrderNumber=number,Status=p.AutoApproveOnCreate?SalesOrderStatus.Approved:SalesOrderStatus.Draft,BranchId=r.BranchId,CustomerId=r.CustomerId,CurrencyId=r.CurrencyId,PaymentTermId=r.PaymentTermId,WarehouseId=r.WarehouseId,OrderDate=r.OrderDate,RequestedShipmentDate=shipmentDate,CustomerReference=r.CustomerReference?.Trim(),ExchangeRate=r.ExchangeRate};var n=0;
  foreach(var l in r.Lines){if(l.Quantity<=0||l.TaxRate is <0 or >100)return ApiResponse<object>.Error("Quantity must be positive and tax rate must be between 0 and 100.",400);if(l.UnitPrice.HasValue&&!p.AllowManualPrice)return ApiResponse<object>.Error("Manual sales price is disabled by sales parameters.",400);var calc=l.UnitPrice.HasValue?null:await pricing.CalculateAsync(new(l.ProductId,l.UnitId,r.CustomerId,r.CustomerGroupId,l.Quantity,r.OrderDate,r.BranchId),ct);if(!l.UnitPrice.HasValue&&calc?.Success!=true)return ApiResponse<object>.Error(calc?.Message??"Price not found.",400);var price=l.UnitPrice??calc!.Data!.UnitPrice;if(price<0||(!p.AllowZeroPrice&&price==0))return ApiResponse<object>.Error("Invalid or zero sales price.",400);var gross=l.Quantity*price;var discount=calc?.Data?.DiscountAmount??0;var discountRate=calc?.Data?.DiscountRate??0;if(discountRate<0||discountRate>p.MaximumDiscountPercent)return ApiResponse<object>.Error($"Discount cannot exceed {p.MaximumDiscountPercent}%.",400);var net=gross-discount;if(net<0)return ApiResponse<object>.Error("Discount cannot exceed line gross amount.",400);var tax=net*l.TaxRate/100m;e.Lines.Add(new SalesOrderLine{LineNumber=++n,ProductId=l.ProductId,UnitId=l.UnitId,StorageLocationId=l.StorageLocationId,InventoryStatusId=l.InventoryStatusId,InventoryLotId=l.InventoryLotId,InventorySerialId=l.InventorySerialId,OrderedQuantity=l.Quantity,UnitPrice=price,DiscountRate=discountRate,DiscountAmount=discount,TaxRate=l.TaxRate,TaxAmount=tax,LineTotal=net+tax,PriceListLineId=calc?.Data?.PriceListLineId,DiscountRuleId=calc?.Data?.DiscountRuleId,Notes=l.Notes});e.Subtotal+=gross;e.DiscountTotal+=discount;e.TaxTotal+=tax;e.GrandTotal+=net+tax;}
  if(e.GrandTotal<p.MinimumOrderAmount)return ApiResponse<object>.Error($"Sales order total must be at least {p.MinimumOrderAmount}.",400);if(p.MaximumOrderAmount>0&&e.GrandTotal>p.MaximumOrderAmount)return ApiResponse<object>.Error($"Sales order total cannot exceed {p.MaximumOrderAmount}.",400);await u.ExecuteInTransactionAsync(async t=>{await u.Repository<SalesOrder>().AddAsync(e,t);await u.SaveChangesAsync(t);},ct);if(reserved is not null)await numberSeries.MarkUsedAsync(reserved.UsageId,e.Id,ct);return ApiResponse<object>.Ok(new{e.Id,e.OrderNumber,e.Status,NumberSeriesUsageId=reserved?.UsageId});
 }
 public async Task<ApiResponse<object>>ConfirmAsync(long id,CancellationToken ct)
 {
  var e=await u.Repository<SalesOrder>().Query(true).Include(x=>x.Lines).FirstOrDefaultAsync(x=>x.Id==id,ct);if(e is null)return ApiResponse<object>.Error("Sales order not found.",404);var p=await parameters.ResolveSettingsAsync(e.BranchId,e.WarehouseId,ct);if(p.RequireApprovalBeforeConfirmation&&e.Status!=SalesOrderStatus.Approved)return ApiResponse<object>.Error("Sales order approval is required before confirmation.",409);if(!p.RequireApprovalBeforeConfirmation&&e.Status is not(SalesOrderStatus.Draft or SalesOrderStatus.Approved))return ApiResponse<object>.Error("Order is not confirmable.",409);if(!p.ReserveInventoryOnConfirmation){e.Status=SalesOrderStatus.Confirmed;e.ConfirmedAt=DateTime.UtcNow;await u.SaveChangesAsync(ct);return ApiResponse<object>.Ok(new{e.Id,e.Status});}
  try{await u.ExecuteInTransactionAsync(async t=>{var anyReserved=false;var allReserved=true;foreach(var line in e.Lines){var b=await u.Repository<InventoryBalance>().FirstOrDefaultAsync(x=>x.ProductId==line.ProductId&&x.WarehouseId==e.WarehouseId&&x.StorageLocationId==line.StorageLocationId&&x.InventoryStatusId==line.InventoryStatusId&&x.InventoryLotId==line.InventoryLotId&&x.InventorySerialId==line.InventorySerialId,true,t);var available=b?.AvailableQuantity??0;if(p.RequireFullReservation&&available<line.OrderedQuantity)throw new InvalidOperationException("Insufficient available inventory for full reservation.");var quantity=Math.Min(available,line.OrderedQuantity);if(quantity<=0){allReserved=false;continue;}b!.ReservedQuantity+=quantity;b.AvailableQuantity-=quantity;line.ReservedQuantity=quantity;if(quantity==line.OrderedQuantity)line.Status=SalesLineStatus.Reserved;else allReserved=false;anyReserved=true;await u.Repository<InventoryReservation>().AddAsync(new InventoryReservation{SourceType="SalesOrder",SourceId=e.Id,SourceLineId=line.Id,ProductId=line.ProductId,WarehouseId=e.WarehouseId,StorageLocationId=line.StorageLocationId,InventoryStatusId=line.InventoryStatusId,InventoryLotId=line.InventoryLotId,InventorySerialId=line.InventorySerialId,Quantity=quantity,Status=ReservationStatus.Active},t);}e.Status=allReserved?SalesOrderStatus.Reserved:anyReserved?SalesOrderStatus.PartiallyReserved:SalesOrderStatus.Confirmed;e.ConfirmedAt=DateTime.UtcNow;await u.SaveChangesAsync(t);},ct);}catch(InvalidOperationException exception){return ApiResponse<object>.Error(exception.Message,409);}return ApiResponse<object>.Ok(new{e.Id,e.Status});
 }
}


