using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore; using System.Security.Cryptography;
using verii_metivon_api.Core.Auth; using verii_metivon_api.Core.Persistence; using verii_metivon_api.Modules.GeneralSettings; using verii_metivon_api.Modules.LandedCosts.Application.Services; using verii_metivon_api.Modules.TradeOperations.Application.Services; using verii_metivon_api.Modules.TradeOperations.Domain.Entities;
namespace verii_metivon_api.Modules.TradeOperations.Api;
[ApiController,Authorize,Route("api/trade-dossiers")]
public sealed class TradeDossiersController(ITradeDossierService service,ILandedCostService landedCosts,MetivonDbContext db,IWebHostEnvironment environment):ControllerBase
{
 [HttpGet]public async Task<IActionResult>List([FromQuery]TradeDossierQuery q,CancellationToken ct){var r=await service.GetPagedAsync(q,ct);return StatusCode(r.StatusCode,r);}
 [HttpGet("{id:long}")]public async Task<IActionResult>Detail(long id,CancellationToken ct){var r=await service.GetDetailAsync(id,ct);return StatusCode(r.StatusCode,r);}
 [HttpPost]public async Task<IActionResult>Create(CreateTradeDossierRequest r,CancellationToken ct){var x=await service.CreateAsync(r,ct);return StatusCode(x.StatusCode,x);}
 [HttpPost("{id:long}/status")]public async Task<IActionResult>Status(long id,ChangeTradeStatusRequest r,CancellationToken ct){var x=await service.ChangeStatusAsync(id,r,ct);return StatusCode(x.StatusCode,x);}
 [HttpPost("{id:long}/declarations")]public async Task<IActionResult>Declaration(long id,CreateCustomsDeclarationRequest r,CancellationToken ct){var x=await service.AddDeclarationAsync(id,r,ct);return StatusCode(x.StatusCode,x);}
 [HttpPost("{id:long}/declarations/{declarationId:long}/status")]public async Task<IActionResult>DeclarationStatus(long id,long declarationId,ChangeCustomsDeclarationStatusRequest r,CancellationToken ct){var x=await service.ChangeDeclarationStatusAsync(id,declarationId,r,ct);return StatusCode(x.StatusCode,x);}
 [HttpPost("{id:long}/links")]public async Task<IActionResult>Link(long id,LinkTradeDocumentRequest r,CancellationToken ct){var x=await service.LinkAsync(id,r,ct);return StatusCode(x.StatusCode,x);}
 [HttpPost("{id:long}/customs-release")]public async Task<IActionResult>Release(long id,ReleaseCustomsStockRequest r,CancellationToken ct){var x=await service.ReleaseAsync(id,r,ct);return StatusCode(x.StatusCode,x);}
 [HttpGet("{id:long}/costs")]public async Task<IActionResult>Costs(long id,CancellationToken ct){var trade=await db.TradeDossiers.AsNoTracking().Where(x=>x.Id==id).Select(x=>new{x.Id,x.Direction,x.Status}).FirstOrDefaultAsync(ct);if(trade is null)return NotFound(ApiResponse<object>.Error("Trade dossier not found.",404));var localCurrencyCode=await db.Set<GeneralSetting>().AsNoTracking().Where(x=>x.ScopeKey=="GLOBAL").Select(x=>x.DefaultCurrencyCode).FirstOrDefaultAsync(ct)??"TRY";var profile=await db.ImportDossiers.AsNoTracking().Where(x=>x.TradeDossierId==id).Select(x=>new{x.Id,Status=x.Status.ToString(),x.AllocationRevision,x.FinalizedAt,x.CurrencyCode,x.TransactionExchangeRate,x.CostingExchangeRate}).FirstOrDefaultAsync(ct);if(profile is null)return Ok(ApiResponse<object>.Ok(new{costProfile=(object?)null,localCurrencyCode,goodsReceipts=Array.Empty<object>(),lines=Array.Empty<object>(),costs=Array.Empty<object>(),totals=new{ForeignGoods=0m,Goods=0m,Costs=0m,Allocated=0m,Final=0m}}));var goodsReceipts=await db.GoodsReceipts.AsNoTracking().Where(x=>x.TradeDossierId==id).OrderByDescending(x=>x.ReceiptDate).ThenByDescending(x=>x.Id).Select(x=>new{x.Id,x.ReceiptNumber,Status=x.Status.ToString(),x.ReceiptDate,x.PostedAt,Warehouse=x.Warehouse.Code,LineCount=x.Lines.Count,Quantity=x.Lines.Sum(l=>l.AcceptedQuantity)}).ToListAsync(ct);var lines=await db.ImportDossierLines.AsNoTracking().Where(x=>x.ImportDossierId==profile.Id).OrderBy(x=>x.LineNumber).Select(x=>new{x.Id,x.LineNumber,x.ProductId,ProductCode=x.Product.Code,ProductName=x.Product.Name,x.Quantity,x.ForeignUnitPrice,x.ForeignGoodsAmount,x.CostingExchangeRate,x.GoodsAmountLocal,x.AllocatedCostLocal,x.FinalUnitCostLocal,x.GoodsReceiptLineId,x.ReceiptTransactionId}).ToListAsync(ct);var costs=await db.ImportDossierCosts.AsNoTracking().Where(x=>x.ImportDossierId==profile.Id).OrderByDescending(x=>x.CreatedAt).Select(x=>new{x.Id,CostType=x.LandedCostType.Name,SourceType=x.SourceType.ToString(),AmountType=x.AmountType.ToString(),AllocationMethod=x.AllocationMethod.ToString(),x.SupplierId,x.InvoiceNumber,x.InvoiceDate,x.PaymentReference,x.PaymentDate,x.CurrencyId,x.CurrencyCode,CurrencySymbol=x.Currency.Symbol,x.ForeignAmount,x.OriginalExchangeRate,AppliedExchangeRate=x.ExchangeRate,x.ExchangeRateDate,x.ExchangeRateSource,x.LocalAmount,x.Description,x.CreatedAt}).ToListAsync(ct);return Ok(ApiResponse<object>.Ok(new{costProfile=profile,localCurrencyCode,goodsReceipts,lines,costs,totals=new{ForeignGoods=lines.Sum(x=>x.ForeignGoodsAmount),Goods=lines.Sum(x=>x.GoodsAmountLocal),Costs=costs.Sum(x=>x.LocalAmount),Allocated=lines.Sum(x=>x.AllocatedCostLocal),Final=lines.Sum(x=>x.GoodsAmountLocal+x.AllocatedCostLocal)}}));}
 [HttpPost("{id:long}/costs")]public async Task<IActionResult>AddCost(long id,AddDossierCostRequest r,CancellationToken ct){var x=await landedCosts.AddTradeDossierCostAsync(id,r,ct);return StatusCode(x.StatusCode,x);}
 [HttpPost("{id:long}/costs/allocate")]public async Task<IActionResult>AllocateCosts(long id,CancellationToken ct){var x=await landedCosts.AllocateTradeDossierAsync(id,ct);return StatusCode(x.StatusCode,x);}
 [HttpPost("{id:long}/costs/finalize")]public async Task<IActionResult>FinalizeCosts(long id,FinalizeDossierRequest r,CancellationToken ct){var x=await landedCosts.FinalizeTradeDossierAsync(id,r,ct);return StatusCode(x.StatusCode,x);}
 [HttpPost("{id:long}/attachments"),RequestSizeLimit(20_971_520)]public async Task<IActionResult>Upload(long id,[FromForm]UploadTradeAttachmentRequest r,CancellationToken ct){if(!await db.TradeDossiers.AnyAsync(x=>x.Id==id,ct))return NotFound(ApiResponse<object>.Error("Trade dossier not found.",404));if(r.File is null||r.File.Length==0||r.File.Length>20_971_520)return BadRequest(ApiResponse<object>.Error("A file up to 20 MB is required.",400));var allowed=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){{".pdf","application/pdf"},{".jpg","image/jpeg"},{".jpeg","image/jpeg"},{".png","image/png"},{".xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},{".xml","application/xml"}};var ext=Path.GetExtension(r.File.FileName);if(!allowed.TryGetValue(ext,out var contentType))return BadRequest(ApiResponse<object>.Error("PDF, JPG, PNG, XLSX or XML files are allowed.",400));if(r.CustomsDeclarationId.HasValue&&!await db.CustomsDeclarations.AnyAsync(x=>x.Id==r.CustomsDeclarationId&&x.TradeDossierId==id,ct))return BadRequest(ApiResponse<object>.Error("Declaration does not belong to dossier.",400));var folder=Path.Combine(environment.ContentRootPath,"App_Data","trade-dossiers",id.ToString());Directory.CreateDirectory(folder);var stored=$"{Guid.NewGuid():N}{ext.ToLowerInvariant()}";var path=Path.Combine(folder,stored);await using(var output=System.IO.File.Create(path))await r.File.CopyToAsync(output,ct);await using var input=System.IO.File.OpenRead(path);var hash=Convert.ToHexString(await SHA256.HashDataAsync(input,ct));if(await db.TradeAttachments.AnyAsync(x=>x.TradeDossierId==id&&x.Sha256==hash,ct)){System.IO.File.Delete(path);return Conflict(ApiResponse<object>.Error("The same file is already attached to this dossier.",409));}var e=new TradeAttachment{TradeDossierId=id,CustomsDeclarationId=r.CustomsDeclarationId,AttachmentType=r.AttachmentType,DocumentNumber=r.DocumentNumber?.Trim(),DocumentDate=r.DocumentDate,OriginalFileName=Path.GetFileName(r.File.FileName),StoredFileName=stored,ContentType=contentType,FileSize=r.File.Length,Sha256=hash,Notes=r.Notes};db.TradeAttachments.Add(e);await db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.Ok(new{e.Id,e.OriginalFileName,e.Sha256}));}
 [HttpGet("{id:long}/attachments/{attachmentId:long}")]public async Task<IActionResult>Download(long id,long attachmentId,CancellationToken ct){var e=await db.TradeAttachments.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==attachmentId&&x.TradeDossierId==id,ct);if(e is null)return NotFound();var path=Path.Combine(environment.ContentRootPath,"App_Data","trade-dossiers",id.ToString(),e.StoredFileName);return System.IO.File.Exists(path)?PhysicalFile(path,e.ContentType,e.OriginalFileName):NotFound();}
}
public sealed class UploadTradeAttachmentRequest{public TradeAttachmentType AttachmentType{get;set;}public long?CustomsDeclarationId{get;set;}public string?DocumentNumber{get;set;}public DateOnly?DocumentDate{get;set;}public string?Notes{get;set;}public IFormFile?File{get;set;}}
