using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore; using System.Security.Cryptography;
using verii_metivon_api.Core.Auth; using verii_metivon_api.Core.Persistence; using verii_metivon_api.Modules.TradeOperations.Application.Services; using verii_metivon_api.Modules.TradeOperations.Domain.Entities;
namespace verii_metivon_api.Modules.TradeOperations.Api;
[ApiController,Authorize,Route("api/trade-dossiers")]
public sealed class TradeDossiersController(ITradeDossierService service,MetivonDbContext db,IWebHostEnvironment environment):ControllerBase
{
 [HttpGet]public async Task<IActionResult>List([FromQuery]TradeDossierQuery q,CancellationToken ct){var r=await service.GetPagedAsync(q,ct);return StatusCode(r.StatusCode,r);}
 [HttpGet("{id:long}")]public async Task<IActionResult>Detail(long id,CancellationToken ct){var r=await service.GetDetailAsync(id,ct);return StatusCode(r.StatusCode,r);}
 [HttpPost]public async Task<IActionResult>Create(CreateTradeDossierRequest r,CancellationToken ct){var x=await service.CreateAsync(r,ct);return StatusCode(x.StatusCode,x);}
 [HttpPost("{id:long}/status")]public async Task<IActionResult>Status(long id,ChangeTradeStatusRequest r,CancellationToken ct){var x=await service.ChangeStatusAsync(id,r,ct);return StatusCode(x.StatusCode,x);}
 [HttpPost("{id:long}/declarations")]public async Task<IActionResult>Declaration(long id,CreateCustomsDeclarationRequest r,CancellationToken ct){var x=await service.AddDeclarationAsync(id,r,ct);return StatusCode(x.StatusCode,x);}
 [HttpPost("{id:long}/declarations/{declarationId:long}/status")]public async Task<IActionResult>DeclarationStatus(long id,long declarationId,ChangeCustomsDeclarationStatusRequest r,CancellationToken ct){var x=await service.ChangeDeclarationStatusAsync(id,declarationId,r,ct);return StatusCode(x.StatusCode,x);}
 [HttpPost("{id:long}/links")]public async Task<IActionResult>Link(long id,LinkTradeDocumentRequest r,CancellationToken ct){var x=await service.LinkAsync(id,r,ct);return StatusCode(x.StatusCode,x);}
 [HttpPost("{id:long}/customs-release")]public async Task<IActionResult>Release(long id,ReleaseCustomsStockRequest r,CancellationToken ct){var x=await service.ReleaseAsync(id,r,ct);return StatusCode(x.StatusCode,x);}
 [HttpPost("{id:long}/attachments"),RequestSizeLimit(20_971_520)]public async Task<IActionResult>Upload(long id,[FromForm]UploadTradeAttachmentRequest r,CancellationToken ct){if(!await db.TradeDossiers.AnyAsync(x=>x.Id==id,ct))return NotFound(ApiResponse<object>.Error("Trade dossier not found.",404));if(r.File is null||r.File.Length==0||r.File.Length>20_971_520)return BadRequest(ApiResponse<object>.Error("A file up to 20 MB is required.",400));var allowed=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){{".pdf","application/pdf"},{".jpg","image/jpeg"},{".jpeg","image/jpeg"},{".png","image/png"},{".xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},{".xml","application/xml"}};var ext=Path.GetExtension(r.File.FileName);if(!allowed.TryGetValue(ext,out var contentType))return BadRequest(ApiResponse<object>.Error("PDF, JPG, PNG, XLSX or XML files are allowed.",400));if(r.CustomsDeclarationId.HasValue&&!await db.CustomsDeclarations.AnyAsync(x=>x.Id==r.CustomsDeclarationId&&x.TradeDossierId==id,ct))return BadRequest(ApiResponse<object>.Error("Declaration does not belong to dossier.",400));var folder=Path.Combine(environment.ContentRootPath,"App_Data","trade-dossiers",id.ToString());Directory.CreateDirectory(folder);var stored=$"{Guid.NewGuid():N}{ext.ToLowerInvariant()}";var path=Path.Combine(folder,stored);await using(var output=System.IO.File.Create(path))await r.File.CopyToAsync(output,ct);await using var input=System.IO.File.OpenRead(path);var hash=Convert.ToHexString(await SHA256.HashDataAsync(input,ct));if(await db.TradeAttachments.AnyAsync(x=>x.TradeDossierId==id&&x.Sha256==hash,ct)){System.IO.File.Delete(path);return Conflict(ApiResponse<object>.Error("The same file is already attached to this dossier.",409));}var e=new TradeAttachment{TradeDossierId=id,CustomsDeclarationId=r.CustomsDeclarationId,AttachmentType=r.AttachmentType,DocumentNumber=r.DocumentNumber?.Trim(),DocumentDate=r.DocumentDate,OriginalFileName=Path.GetFileName(r.File.FileName),StoredFileName=stored,ContentType=contentType,FileSize=r.File.Length,Sha256=hash,Notes=r.Notes};db.TradeAttachments.Add(e);await db.SaveChangesAsync(ct);return Ok(ApiResponse<object>.Ok(new{e.Id,e.OriginalFileName,e.Sha256}));}
 [HttpGet("{id:long}/attachments/{attachmentId:long}")]public async Task<IActionResult>Download(long id,long attachmentId,CancellationToken ct){var e=await db.TradeAttachments.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==attachmentId&&x.TradeDossierId==id,ct);if(e is null)return NotFound();var path=Path.Combine(environment.ContentRootPath,"App_Data","trade-dossiers",id.ToString(),e.StoredFileName);return System.IO.File.Exists(path)?PhysicalFile(path,e.ContentType,e.OriginalFileName):NotFound();}
}
public sealed class UploadTradeAttachmentRequest{public TradeAttachmentType AttachmentType{get;set;}public long?CustomsDeclarationId{get;set;}public string?DocumentNumber{get;set;}public DateOnly?DocumentDate{get;set;}public string?Notes{get;set;}public IFormFile?File{get;set;}}
