using System.Data;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using verii_metivon_api.Core.Persistence;
using verii_metivon_api.Modules.Parameters.Domain.Entities;
using verii_metivon_api.Modules.Sales.Domain.Entities;

namespace verii_metivon_api.Modules.Sales.Application.Parameters;

public sealed record SalesOrderParametersDto(long?BranchId,long?WarehouseId,bool IsAutomatic,bool AllowManual,string Format,long NextNumber,int IncrementBy,long MinimumNumber,long MaximumNumber,bool RequireApprovalBeforeConfirmation,bool AutoApproveOnCreate,bool RequireRequestedShipmentDate,int DefaultShipmentLeadTimeDays,bool AllowPastOrderDate,bool RequireCustomerReference,bool RequireActiveCustomer,int MaximumLinesPerOrder,bool AllowManualPrice,bool AllowZeroPrice,decimal MaximumDiscountPercent,decimal MinimumOrderAmount,decimal MaximumOrderAmount,bool ReserveInventoryOnConfirmation,bool RequireFullReservation,string Preview);
public sealed record SaveSalesOrderParametersRequest(long?BranchId,long?WarehouseId,bool IsAutomatic,bool AllowManual,string Format,long NextNumber,int IncrementBy,long MinimumNumber,long MaximumNumber,bool RequireApprovalBeforeConfirmation,bool AutoApproveOnCreate,bool RequireRequestedShipmentDate,int DefaultShipmentLeadTimeDays,bool AllowPastOrderDate,bool RequireCustomerReference,bool RequireActiveCustomer,int MaximumLinesPerOrder,bool AllowManualPrice,bool AllowZeroPrice,decimal MaximumDiscountPercent,decimal MinimumOrderAmount,decimal MaximumOrderAmount,bool ReserveInventoryOnConfirmation,bool RequireFullReservation);
public interface ISalesOrderParameterService{Task<SalesOrderParametersDto>GetAsync(long?branchId,long?warehouseId,CancellationToken ct);Task<SalesOrderParametersDto>SaveAsync(SaveSalesOrderParametersRequest r,CancellationToken ct);Task<SalesOrderParameterSettings>ResolveSettingsAsync(long?branchId,long?warehouseId,CancellationToken ct);Task<string>ResolveOrderNumberAsync(string?requested,long?branchId,CancellationToken ct);}

public sealed class SalesOrderParameterService(MetivonDbContext db):ISalesOrderParameterService
{
 const string Module="Sales",Reference="SalesOrderNumber",Fallback="SO-{YYYY}-{NUMBER:6}";static readonly Regex Token=new(@"\{NUMBER(?::(?<length>\d{1,2}))?\}",RegexOptions.Compiled|RegexOptions.IgnoreCase);
 public async Task<SalesOrderParametersDto>GetAsync(long?branchId,long?warehouseId,CancellationToken ct){var s=await Sequence(branchId,ct);var p=await ResolveSettingsAsync(branchId,warehouseId,ct);return new(branchId,warehouseId,s.IsAutomatic,s.AllowManual,s.Format,s.CurrentNumber,s.IncrementBy,s.MinimumNumber,s.MaximumNumber,p.RequireApprovalBeforeConfirmation,p.AutoApproveOnCreate,p.RequireRequestedShipmentDate,p.DefaultShipmentLeadTimeDays,p.AllowPastOrderDate,p.RequireCustomerReference,p.RequireActiveCustomer,p.MaximumLinesPerOrder,p.AllowManualPrice,p.AllowZeroPrice,p.MaximumDiscountPercent,p.MinimumOrderAmount,p.MaximumOrderAmount,p.ReserveInventoryOnConfirmation,p.RequireFullReservation,FormatNumber(s.Format,s.CurrentNumber,await BranchCode(branchId,ct)));}
 public async Task<SalesOrderParametersDto>SaveAsync(SaveSalesOrderParametersRequest r,CancellationToken ct){Validate(r);await ValidateRefs(r,ct);await using var tx=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);var s=await db.NumberSequences.FirstOrDefaultAsync(x=>x.Module==Module&&x.Reference==Reference&&x.BranchId==r.BranchId,ct);if(s is null){s=new NumberSequence{Module=Module,Reference=Reference,BranchId=r.BranchId};db.Add(s);}s.Format=r.Format.Trim();s.CurrentNumber=r.NextNumber;s.IncrementBy=r.IncrementBy;s.MinimumNumber=r.MinimumNumber;s.MaximumNumber=r.MaximumNumber;s.IsAutomatic=r.IsAutomatic;s.AllowManual=r.AllowManual;s.IsActive=true;var p=await db.SalesOrderParameterSettings.FirstOrDefaultAsync(x=>x.BranchId==r.BranchId&&x.WarehouseId==r.WarehouseId,ct);if(p is null){p=new SalesOrderParameterSettings{BranchId=r.BranchId,WarehouseId=r.WarehouseId};db.Add(p);}p.RequireApprovalBeforeConfirmation=r.RequireApprovalBeforeConfirmation;p.AutoApproveOnCreate=r.AutoApproveOnCreate;p.RequireRequestedShipmentDate=r.RequireRequestedShipmentDate;p.DefaultShipmentLeadTimeDays=r.DefaultShipmentLeadTimeDays;p.AllowPastOrderDate=r.AllowPastOrderDate;p.RequireCustomerReference=r.RequireCustomerReference;p.RequireActiveCustomer=r.RequireActiveCustomer;p.MaximumLinesPerOrder=r.MaximumLinesPerOrder;p.AllowManualPrice=r.AllowManualPrice;p.AllowZeroPrice=r.AllowZeroPrice;p.MaximumDiscountPercent=r.MaximumDiscountPercent;p.MinimumOrderAmount=r.MinimumOrderAmount;p.MaximumOrderAmount=r.MaximumOrderAmount;p.ReserveInventoryOnConfirmation=r.ReserveInventoryOnConfirmation;p.RequireFullReservation=r.RequireFullReservation;await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return await GetAsync(r.BranchId,r.WarehouseId,ct);}
 public async Task<SalesOrderParameterSettings>ResolveSettingsAsync(long?branchId,long?warehouseId,CancellationToken ct)=>await db.SalesOrderParameterSettings.AsNoTracking().Where(x=>(x.BranchId==branchId||x.BranchId==null)&&(x.WarehouseId==warehouseId||x.WarehouseId==null)).OrderByDescending(x=>x.WarehouseId.HasValue).ThenByDescending(x=>x.BranchId.HasValue).FirstOrDefaultAsync(ct)??new SalesOrderParameterSettings{BranchId=branchId,WarehouseId=warehouseId};
 public async Task<string>ResolveOrderNumberAsync(string?requested,long?branchId,CancellationToken ct){var s=await Sequence(branchId,ct);var manual=requested?.Trim().ToUpperInvariant();if(!string.IsNullOrWhiteSpace(manual)){if(s.IsAutomatic&&!s.AllowManual)throw new InvalidOperationException("Manual sales order number is disabled by sales parameters.");return manual;}if(!s.IsAutomatic)throw new InvalidOperationException("Sales order number is required because automatic numbering is disabled.");return FormatNumber(s.Format,await Consume(s,ct),await BranchCode(branchId,ct));}
 async Task<NumberSequence>Sequence(long?branchId,CancellationToken ct)=>await db.NumberSequences.AsNoTracking().Where(x=>x.Module==Module&&x.Reference==Reference&&x.IsActive&&(x.BranchId==branchId||x.BranchId==null)).OrderByDescending(x=>x.BranchId.HasValue).FirstOrDefaultAsync(ct)??new NumberSequence{Module=Module,Reference=Reference,BranchId=branchId,Format=Fallback,CurrentNumber=1,IncrementBy=1,MinimumNumber=1,MaximumNumber=999999999,IsAutomatic=true,AllowManual=true};
 async Task ValidateRefs(SaveSalesOrderParametersRequest r,CancellationToken ct){if(r.BranchId.HasValue&&!await db.Branches.AnyAsync(x=>x.Id==r.BranchId&&x.IsActive,ct))throw new ArgumentException("Selected branch is not active.");if(r.WarehouseId.HasValue&&!await db.Warehouses.AnyAsync(x=>x.Id==r.WarehouseId&&x.IsActive&&(!r.BranchId.HasValue||x.BranchId==r.BranchId),ct))throw new ArgumentException("Selected warehouse is not active or does not belong to the selected branch.");}
 static void Validate(SaveSalesOrderParametersRequest r){if(!Token.IsMatch(r.Format)||r.Format.Length>120||FormatNumber(r.Format,r.NextNumber,"0").Length>40)throw new ArgumentException("Sales order mask is invalid or generates more than 40 characters.");if(r.IncrementBy<1||r.MinimumNumber<0||r.NextNumber<r.MinimumNumber||r.MaximumNumber<r.NextNumber)throw new ArgumentException("Document number range is invalid.");if(r.DefaultShipmentLeadTimeDays is <0 or >3650)throw new ArgumentException("Default shipment lead time is invalid.");if(r.MaximumLinesPerOrder is <1 or >10000)throw new ArgumentException("Maximum order line count is invalid.");if(r.MaximumDiscountPercent is <0 or >100)throw new ArgumentException("Maximum discount must be between 0 and 100.");if(r.MinimumOrderAmount<0||r.MaximumOrderAmount<0||(r.MaximumOrderAmount>0&&r.MaximumOrderAmount<r.MinimumOrderAmount))throw new ArgumentException("Sales order amount limits are invalid.");if(r.AutoApproveOnCreate&&!r.RequireApprovalBeforeConfirmation)throw new ArgumentException("Automatic approval requires approval control to be enabled.");if(r.RequireFullReservation&&!r.ReserveInventoryOnConfirmation)throw new ArgumentException("Full reservation requires reservation on confirmation.");}
 async Task<string>BranchCode(long?id,CancellationToken ct)=>id.HasValue?await db.Branches.AsNoTracking().Where(x=>x.Id==id).Select(x=>x.Code).FirstOrDefaultAsync(ct)??"0":"0";
 async Task<long>Consume(NumberSequence s,CancellationToken ct){var stored=await db.NumberSequences.FirstOrDefaultAsync(x=>x.Module==Module&&x.Reference==Reference&&x.BranchId==s.BranchId,ct);if(stored is null){stored=new NumberSequence{Module=Module,Reference=Reference,BranchId=s.BranchId,Format=s.Format,CurrentNumber=s.CurrentNumber,IncrementBy=s.IncrementBy,MinimumNumber=s.MinimumNumber,MaximumNumber=s.MaximumNumber,IsAutomatic=s.IsAutomatic,AllowManual=s.AllowManual,IsActive=true};db.Add(stored);await db.SaveChangesAsync(ct);}var c=db.Database.GetDbConnection();if(c.State!=ConnectionState.Open)await c.OpenAsync(ct);await using var cmd=c.CreateCommand();cmd.Transaction=db.Database.CurrentTransaction?.GetDbTransaction();cmd.CommandText="UPDATE RII_NUMBER_SEQUENCES WITH (UPDLOCK, ROWLOCK) SET CurrentNumber=CurrentNumber+IncrementBy,UpdatedAt=SYSUTCDATETIME() OUTPUT DELETED.CurrentNumber WHERE Id=@id AND IsActive=1 AND CurrentNumber<=MaximumNumber";var p=cmd.CreateParameter();p.ParameterName="@id";p.Value=stored.Id;cmd.Parameters.Add(p);var value=await cmd.ExecuteScalarAsync(ct);return value is null||value==DBNull.Value?throw new InvalidOperationException("Sales order number sequence could not be consumed."):Convert.ToInt64(value);}
 static string FormatNumber(string f,long n,string branch){var result=f.Replace("{BRANCH}",branch,StringComparison.OrdinalIgnoreCase).Replace("{YYYY}",DateTime.UtcNow.ToString("yyyy"),StringComparison.OrdinalIgnoreCase).Replace("{YY}",DateTime.UtcNow.ToString("yy"),StringComparison.OrdinalIgnoreCase).Replace("{MM}",DateTime.UtcNow.ToString("MM"),StringComparison.OrdinalIgnoreCase);return Token.Replace(result,m=>n.ToString().PadLeft(Math.Clamp(int.TryParse(m.Groups["length"].Value,out var l)?l:1,1,18),'0'));}
}
