using verii_metivon_api.Core.Domain;
namespace verii_metivon_api.Modules.EDocuments.Domain.Entities;
public enum ElectronicDocumentType{EInvoice=1,EArchiveInvoice=2,EDespatch=3}public enum ElectronicDocumentDirection{Outgoing=1,Incoming=2}public enum ElectronicDocumentStatus{Draft=0,ValidationFailed=1,Ready=2,Queued=3,Submitting=4,Submitted=5,Delivered=6,Accepted=7,Rejected=8,Cancelled=9,Failed=10}public enum EDocumentProviderType{CrsSoft=1}
public sealed class CompanyLegalProfile:Entity{public long BranchId{get;set;}public string TaxNumber{get;set;}=string.Empty;public string TaxOffice{get;set;}=string.Empty;public string LegalName{get;set;}=string.Empty;public string CountryCode{get;set;}="TR";public string City{get;set;}=string.Empty;public string District{get;set;}=string.Empty;public string Address{get;set;}=string.Empty;public string?Email{get;set;}public string?Phone{get;set;}public string?MersisNumber{get;set;}public string?TradeRegistryNumber{get;set;}public bool IsEInvoiceRegistered{get;set;}public bool IsEDespatchRegistered{get;set;}public bool IsActive{get;set;}=true;}
public sealed class EDocumentProviderConfiguration:Entity{public long BranchId{get;set;}public EDocumentProviderType ProviderType{get;set;}public string Environment{get;set;}="Test";public string InvoiceServiceUrl{get;set;}=string.Empty;public string DespatchServiceUrl{get;set;}=string.Empty;public string CredentialReference{get;set;}=string.Empty;public int TimeoutSeconds{get;set;}=60;public int MaximumRetryCount{get;set;}=5;public bool IsActive{get;set;}=true;}
public sealed class ElectronicDocument:Entity{public Guid Uuid{get;set;}=Guid.NewGuid();public ElectronicDocumentType DocumentType{get;set;}public ElectronicDocumentDirection Direction{get;set;}public ElectronicDocumentStatus Status{get;set;}public long BranchId{get;set;}public string DocumentNumber{get;set;}=string.Empty;public DateTime IssueDate{get;set;}public string Scenario{get;set;}=string.Empty;public string SourceType{get;set;}=string.Empty;public long SourceId{get;set;}public string?ProviderDocumentId{get;set;}public string?EnvelopeId{get;set;}public string?PayloadXml{get;set;}public string?PayloadHash{get;set;}public string?LastErrorCode{get;set;}public string?LastErrorMessage{get;set;}public DateTime?SubmittedAt{get;set;}public DateTime?CompletedAt{get;set;}public int AttemptCount{get;set;}public DateTime?NextAttemptAt{get;set;}public ICollection<ElectronicDocumentStatusHistory>History{get;set;}=new List<ElectronicDocumentStatusHistory>();}
public sealed class ElectronicDocumentStatusHistory:Entity{public long ElectronicDocumentId{get;set;}public ElectronicDocument ElectronicDocument{get;set;}=null!;public ElectronicDocumentStatus FromStatus{get;set;}public ElectronicDocumentStatus ToStatus{get;set;}public string?ProviderCode{get;set;}public string?Description{get;set;}public string?RawResponse{get;set;}public DateTime OccurredAt{get;set;}=DateTime.UtcNow;}
public sealed class EDocumentParameterSettings:Entity
{
 public long BranchId{get;set;}public Branch Branch{get;set;}=null!;
 public EDocumentProviderType ProviderType{get;set;}=EDocumentProviderType.CrsSoft;public string ProviderEnvironment{get;set;}="Test";
 public string DefaultInvoiceScenario{get;set;}="TEMELFATURA";public string DefaultArchiveInvoiceScenario{get;set;}="EARSIVFATURA";public string DefaultDespatchScenario{get;set;}="TEMELIRSALIYE";
 public bool AutoQueueAfterCreate{get;set;}public bool RequireUblValidation{get;set;}=true;public bool RequireCompanyLegalProfile{get;set;}=true;public bool RequireTaxNumberValidation{get;set;}=true;
 public bool PreventDuplicateSourceDocument{get;set;}=true;public bool FallbackToEArchive{get;set;}=true;public bool RequireRecipientMailboxForEInvoice{get;set;}=true;public bool SendEArchiveByEmail{get;set;}=true;public bool AllowManualScenario{get;set;}
 public int RetryDelayMinutes{get;set;}=15;public int StatusPollingIntervalMinutes{get;set;}=10;public int ArchiveRetentionYears{get;set;}=10;public int MaximumXmlSizeKb{get;set;}=5120;
 public string DefaultCurrencyCode{get;set;}="TRY";public byte[]RowVersion{get;set;}=[];
}
