using verii_metivon_api.Core.Domain;using verii_metivon_api.Modules.Products.Domain.Entities;using verii_metivon_api.Modules.Warehouses.Domain.Entities;
namespace verii_metivon_api.Modules.Sales.Domain.Entities;public enum SalesOrderStatus{Draft=0,PendingApproval=1,Approved=2,Confirmed=3,PartiallyReserved=4,Reserved=5,PartiallyShipped=6,Shipped=7,Invoiced=8,Cancelled=9,Closed=10}public enum SalesLineStatus{Open=0,Reserved=1,PartiallyShipped=2,Shipped=3,Cancelled=4}public sealed class SalesOrder:Entity{public string OrderNumber{get;set;}=string.Empty;public SalesOrderStatus Status{get;set;}public long BranchId{get;set;}public long CustomerId{get;set;}public BusinessPartner Customer{get;set;}=null!;public long CurrencyId{get;set;}public Currency Currency{get;set;}=null!;public long PaymentTermId{get;set;}public long WarehouseId{get;set;}public Warehouse Warehouse{get;set;}=null!;public DateOnly OrderDate{get;set;}public DateOnly?RequestedShipmentDate{get;set;}public string?CustomerReference{get;set;}public decimal ExchangeRate{get;set;}=1;public decimal Subtotal{get;set;}public decimal DiscountTotal{get;set;}public decimal TaxTotal{get;set;}public decimal GrandTotal{get;set;}public DateTime?ConfirmedAt{get;set;}public ICollection<SalesOrderLine>Lines{get;set;}=new List<SalesOrderLine>();}public sealed class SalesOrderLine:Entity{public long SalesOrderId{get;set;}public SalesOrder SalesOrder{get;set;}=null!;public int LineNumber{get;set;}public SalesLineStatus Status{get;set;}public long ProductId{get;set;}public Product Product{get;set;}=null!;public long UnitId{get;set;}public long StorageLocationId{get;set;}public long InventoryStatusId{get;set;}public long?InventoryLotId{get;set;}public long?InventorySerialId{get;set;}public decimal OrderedQuantity{get;set;}public decimal ReservedQuantity{get;set;}public decimal ShippedQuantity{get;set;}public decimal UnitPrice{get;set;}public decimal DiscountRate{get;set;}public decimal DiscountAmount{get;set;}public decimal TaxRate{get;set;}public decimal TaxAmount{get;set;}public decimal LineTotal{get;set;}public long?PriceListLineId{get;set;}public long?DiscountRuleId{get;set;}public string?Notes{get;set;}}
public sealed class SalesOrderParameterSettings:Entity
{
 public long?BranchId{get;set;}public Branch?Branch{get;set;}public long?WarehouseId{get;set;}public Warehouse?Warehouse{get;set;}
 public bool RequireApprovalBeforeConfirmation{get;set;}public bool AutoApproveOnCreate{get;set;}public bool RequireRequestedShipmentDate{get;set;}=true;public int DefaultShipmentLeadTimeDays{get;set;}=1;public bool AllowPastOrderDate{get;set;}public bool RequireCustomerReference{get;set;}public bool RequireActiveCustomer{get;set;}=true;
 public int MaximumLinesPerOrder{get;set;}=200;public bool AllowManualPrice{get;set;}=true;public bool AllowZeroPrice{get;set;}public decimal MaximumDiscountPercent{get;set;}=100;public decimal MinimumOrderAmount{get;set;}public decimal MaximumOrderAmount{get;set;}
 public bool ReserveInventoryOnConfirmation{get;set;}=true;public bool RequireFullReservation{get;set;}=true;public byte[]RowVersion{get;set;}=[];
}
